import { createHash } from "node:crypto";
import type { PrismaClient } from "@prisma/client";
import { allocateExact, calculateConfiguredTax, calculateConsolidation, calculateRevenueRecognition } from "../src/domain/accounting";

const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");

type SeedAccountingInput = {
  organizationId: string;
  userId: string;
  economicGroupId: string;
  holdingCompanyId: string;
  companyId: string;
  projectId: string;
  costCenterId?: string | null;
  economicItemId?: string | null;
  budgetTotal: string;
  contractId: string;
  contractAmount: string;
  measurementId: string;
  measurementAmount: string;
  payableId: string;
  intercompanyId: string;
  intercompanyAmount: string;
  saleId: string;
  salesContractId: string;
  soldPrice: string;
  salesUnits: Array<{ id: string; code: string; privateAreaM2: string }>;
};

export async function seedAccountingDemo(prisma: PrismaClient, input: SeedAccountingInput) {
  const chart = await prisma.chartOfAccounts.upsert({
    where: { organizationId_code: { organizationId: input.organizationId, code: "REDE-DEMO" } },
    update: { name: "Plano de Contas Gerencial REDE — Demonstração", economicGroupId: input.economicGroupId },
    create: { organizationId: input.organizationId, economicGroupId: input.economicGroupId, code: "REDE-DEMO", name: "Plano de Contas Gerencial REDE — Demonstração", createdById: input.userId },
  });
  const chartVersion = await prisma.chartOfAccountsVersion.upsert({
    where: { chartId_version: { chartId: chart.id, version: 1 } },
    update: { status: "ACTIVE", approvedById: input.userId, approvedAt: new Date("2026-08-22"), checksum: hash("REDE-DEMO-v1") },
    create: { chartId: chart.id, version: 1, status: "ACTIVE", effectiveFrom: new Date("2026-01-01"), approvedById: input.userId, approvedAt: new Date("2026-08-22"), checksum: hash("REDE-DEMO-v1"), createdById: input.userId },
  });
  const accountDefinitions = [
    ["1", "Ativo", "ASSET", "DEBIT", false, null], ["1.1", "Caixa e bancos", "ASSET", "DEBIT", true, "1"], ["1.2", "Clientes e recebíveis", "ASSET", "DEBIT", true, "1"], ["1.3", "Estoque imobiliário", "ASSET", "DEBIT", true, "1"], ["1.4", "Adiantamentos", "ASSET", "DEBIT", true, "1"],
    ["2", "Passivo", "LIABILITY", "CREDIT", false, null], ["2.1", "Fornecedores", "LIABILITY", "CREDIT", true, "2"], ["2.2", "Tributos a recolher", "LIABILITY", "CREDIT", true, "2"], ["2.3", "Intercompany a pagar", "LIABILITY", "CREDIT", true, "2"],
    ["3", "Patrimônio líquido", "EQUITY", "CREDIT", true, null], ["4", "Receita imobiliária", "REVENUE", "CREDIT", true, null], ["5", "Custo imobiliário", "COST", "DEBIT", false, null], ["5.1", "Custo de obra apropriável", "COST", "DEBIT", true, "5"], ["5.2", "Custo das unidades vendidas", "COST", "DEBIT", true, "5"], ["6", "Despesas operacionais", "EXPENSE", "DEBIT", false, null], ["6.1", "Despesas administrativas", "EXPENSE", "DEBIT", true, "6"], ["7", "Resultado financeiro", "FINANCIAL_RESULT", "DEBIT", true, null], ["8", "Contas de controle", "CONTROL", "DEBIT", true, null],
  ] as const;
  const accounts = new Map<string, Awaited<ReturnType<typeof prisma.ledgerAccount.upsert>>>();
  for (const [code, name, category, normalBalance, isPosting, parentCode] of accountDefinitions) {
    const account = await prisma.ledgerAccount.upsert({ where: { versionId_code: { versionId: chartVersion.id, code } }, update: { name, category, normalBalance, isPosting, isActive: true, parentId: parentCode ? accounts.get(parentCode)?.id : null }, create: { versionId: chartVersion.id, code, name, category, normalBalance, isPosting, parentId: parentCode ? accounts.get(parentCode)?.id : null, managerialGroup: category, createdById: input.userId } });
    accounts.set(code, account);
  }
  await prisma.companyChartAssignment.upsert({ where: { companyId_effectiveFrom: { companyId: input.companyId, effectiveFrom: new Date("2026-01-01") } }, update: { organizationId: input.organizationId, versionId: chartVersion.id, effectiveTo: null }, create: { organizationId: input.organizationId, companyId: input.companyId, versionId: chartVersion.id, effectiveFrom: new Date("2026-01-01"), overrides: { demonstration: true }, createdById: input.userId } });

  async function policy(policyType: string, name: string, parameters: object) {
    const existing = await prisma.accountingPolicy.findFirst({ where: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, policyType, name, version: 1 } });
    return existing ?? prisma.accountingPolicy.create({ data: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, policyType, name, version: 1, status: "ACTIVE", effectiveFrom: new Date("2026-01-01"), parameters, approvedById: input.userId, approvedAt: new Date("2026-08-22"), createdById: input.userId } });
  }
  const costPolicy = await policy("COST_RECOGNITION", "Competência por medição aprovada — demonstração", { trigger: "APPROVED_MEASUREMENT", contractIsCommitmentOnly: true, fiscalDocumentConfirmsObligation: true, paymentIsCashOnly: true });
  const revenuePolicy = await policy("REVENUE_RECOGNITION", "Reconhecimento parametrizado de receita — demonstração", { method: "DEMONSTRATION_PROGRESS", recognitionRate: "0.25", requiresProfessionalApproval: true });
  const inventoryPolicy = await policy("INVENTORY", "Apropriação de estoque por área privativa — demonstração", { eligibleCosts: ["LAND", "CONSTRUCTION", "DESIGN"], driver: "PRIVATE_AREA", residualRule: "LAST_ELIGIBLE_UNIT" });
  await policy("CLOSING", "Fechamento mensal e materialidade — demonstração", { financialCloseRequired: true, materialityAmount: "1000", silentRetroactivityBlocked: true });

  async function mapping(sourceModule: string, sourceType: string, eventType: string, debit: string, credit: string, historyTemplate: string, policyId = costPolicy.id) {
    return prisma.accountingMappingRule.upsert({ where: { organizationId_sourceModule_sourceType_eventType_version_priority: { organizationId: input.organizationId, sourceModule, sourceType, eventType, version: 1, priority: 100 } }, update: { companyId: input.companyId, projectId: input.projectId, policyId, debitAccountId: accounts.get(debit)!.id, creditAccountId: accounts.get(credit)!.id, status: "ACTIVE", criteria: { companyId: input.companyId, projectId: input.projectId } }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, policyId, sourceModule, sourceType, eventType, version: 1, priority: 100, status: "ACTIVE", effectiveFrom: new Date("2026-01-01"), criteria: { companyId: input.companyId, projectId: input.projectId }, debitAccountId: accounts.get(debit)!.id, creditAccountId: accounts.get(credit)!.id, historyTemplate, createdById: input.userId, approvedById: input.userId } });
  }
  const measurementMapping = await mapping("PROCUREMENT", "MEASUREMENT", "COST_RECOGNITION", "1.3", "2.1", "Medição aprovada apropriada ao estoque");
  const paymentMapping = await mapping("FINANCIAL", "PAYABLE_PAYMENT", "CASH_SETTLEMENT", "2.1", "1.1", "Pagamento com baixa de fornecedor");
  const revenueMapping = await mapping("SALES", "SALES_CONTRACT", "REVENUE_RECOGNITION", "1.2", "4", "Receita imobiliária conforme política", revenuePolicy.id);
  const cogsMapping = await mapping("SALES", "SALES_UNIT", "INVENTORY_WRITE_OFF", "5.2", "1.3", "Baixa de custo da unidade conforme política", inventoryPolicy.id);

  const september = await prisma.accountingPeriod.upsert({ where: { organizationId_companyId_referenceMonth: { organizationId: input.organizationId, companyId: input.companyId, referenceMonth: new Date("2026-09-01") } }, update: { status: "CLOSED", closedById: input.userId, closedAt: new Date("2026-10-05"), checklistSnapshot: { financial: true, apAr: true, measurements: true, provisions: true, tax: true, intercompany: true, inventory: true, trialBalance: true }, closeChecksum: hash("close-2026-09"), updatedById: input.userId }, create: { organizationId: input.organizationId, companyId: input.companyId, referenceMonth: new Date("2026-09-01"), status: "CLOSED", closedById: input.userId, closedAt: new Date("2026-10-05"), checklistSnapshot: { financial: true, apAr: true, measurements: true, provisions: true, tax: true, intercompany: true, inventory: true, trialBalance: true }, closeChecksum: hash("close-2026-09"), createdById: input.userId, updatedById: input.userId } });
  await prisma.ledgerSnapshot.upsert({ where: { periodId_snapshotType: { periodId: september.id, snapshotType: "CLOSING_TRIAL_BALANCE" } }, update: { balances: [], totalDebit: "0", totalCredit: "0", checksum: hash("close-2026-09"), createdById: input.userId }, create: { organizationId: input.organizationId, companyId: input.companyId, periodId: september.id, snapshotType: "CLOSING_TRIAL_BALANCE", balances: [], totalDebit: "0", totalCredit: "0", checksum: hash("close-2026-09"), createdById: input.userId } });
  const october = await prisma.accountingPeriod.upsert({ where: { organizationId_companyId_referenceMonth: { organizationId: input.organizationId, companyId: input.companyId, referenceMonth: new Date("2026-10-01") } }, update: { status: "OPEN", updatedById: input.userId }, create: { organizationId: input.organizationId, companyId: input.companyId, referenceMonth: new Date("2026-10-01"), status: "OPEN", createdById: input.userId, updatedById: input.userId } });

  async function event(data: { key: string; mappingId?: string; policyId?: string; sourceModule: string; sourceType: string; sourceId: string; sourceVersion?: string; eventType: string; amount: string; status: "VALIDATED" | "CLASSIFIED" | "POSTED"; competenceDate: Date; economicKey: string; occurredAt?: Date; documentIssuedAt?: Date; settledAt?: Date }) {
    return prisma.accountingEvent.upsert({ where: { organizationId_idempotencyKey: { organizationId: input.organizationId, idempotencyKey: data.key } }, update: { status: data.status, mappingRuleId: data.mappingId ?? null, policyId: data.policyId ?? null, payloadChecksum: hash(data), normalizedPayload: data, provenance: { seed: "9G", sourceId: data.sourceId } }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, costCenterId: input.costCenterId ?? null, economicItemId: input.economicItemId ?? null, periodId: october.id, policyId: data.policyId ?? null, mappingRuleId: data.mappingId ?? null, sourceModule: data.sourceModule, sourceType: data.sourceType, sourceId: data.sourceId, sourceVersion: data.sourceVersion ?? "1", economicIdentityKey: data.economicKey, eventType: data.eventType, eventVersion: 1, idempotencyKey: data.key, payloadChecksum: hash(data), occurredAt: data.occurredAt ?? data.competenceDate, competenceDate: data.competenceDate, documentIssuedAt: data.documentIssuedAt ?? null, proposedAccountingDate: data.status === "POSTED" ? data.competenceDate : null, settledAt: data.settledAt ?? null, grossAmount: data.amount, netAmount: data.amount, status: data.status, normalizedPayload: data, provenance: { seed: "9G", sourceId: data.sourceId }, createdById: input.userId } });
  }
  const economicCostKey = `${input.organizationId}:${input.companyId}:construction:${input.measurementId}`;
  await event({ key: `9G:contract:${input.contractId}:1`, sourceModule: "PROCUREMENT", sourceType: "CONTRACT", sourceId: input.contractId, eventType: "COMMITMENT", amount: input.contractAmount, status: "VALIDATED", competenceDate: new Date("2026-09-01"), economicKey: economicCostKey });
  const measurementEvent = await event({ key: `9G:measurement:${input.measurementId}:1`, mappingId: measurementMapping.id, policyId: costPolicy.id, sourceModule: "PROCUREMENT", sourceType: "MEASUREMENT", sourceId: input.measurementId, eventType: "COST_RECOGNITION", amount: input.measurementAmount, status: "POSTED", competenceDate: new Date("2026-10-01"), economicKey: economicCostKey, documentIssuedAt: new Date("2026-10-01") });
  await event({ key: `9G:fiscal-document:${input.measurementId}:1`, sourceModule: "FISCAL", sourceType: "DOCUMENT_REFERENCE", sourceId: input.measurementId, eventType: "OBLIGATION_CONFIRMATION", amount: input.measurementAmount, status: "VALIDATED", competenceDate: new Date("2026-10-01"), economicKey: economicCostKey, documentIssuedAt: new Date("2026-10-05") });
  const paymentEvent = await event({ key: `9G:payment:${input.payableId}:1`, mappingId: paymentMapping.id, policyId: costPolicy.id, sourceModule: "FINANCIAL", sourceType: "PAYABLE_PAYMENT", sourceId: input.payableId, eventType: "CASH_SETTLEMENT", amount: input.measurementAmount, status: "POSTED", competenceDate: new Date("2026-10-01"), economicKey: economicCostKey, settledAt: new Date("2026-10-15") });

  async function entry(eventId: string, number: string, description: string, debitCode: string, creditCode: string, amount: string) {
    const existing = await prisma.accountingEntry.findFirst({ where: { organizationId: input.organizationId, companyId: input.companyId, entryNumber: number } });
    if (existing) return existing;
    return prisma.accountingEntry.create({ data: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, periodId: october.id, eventId, policyId: costPolicy.id, entryNumber: number, accountingDate: new Date("2026-10-01"), competenceDate: new Date("2026-10-01"), description, status: "POSTED", totalDebit: amount, totalCredit: amount, checksum: hash({ number, amount }), postedById: input.userId, postedAt: new Date("2026-10-01"), createdById: input.userId, lines: { create: [{ accountId: accounts.get(debitCode)!.id, sequence: 1, side: "DEBIT", amount, history: description, projectId: input.projectId, costCenterId: input.costCenterId ?? null, economicItemId: input.economicItemId ?? null }, { accountId: accounts.get(creditCode)!.id, sequence: 2, side: "CREDIT", amount, history: description, projectId: input.projectId, costCenterId: input.costCenterId ?? null, economicItemId: input.economicItemId ?? null }] } } });
  }
  const measurementEntry = await entry(measurementEvent.id, "202610-000001", "Medição reconhecida uma única vez por competência", "1.3", "2.1", input.measurementAmount);
  await entry(paymentEvent.id, "202610-000002", "Pagamento: baixa de fornecedor contra caixa", "2.1", "1.1", input.measurementAmount);

  await prisma.accountingProvision.upsert({ where: { organizationId_economicIdentityKey_competenceDate: { organizationId: input.organizationId, economicIdentityKey: `${input.organizationId}:${input.companyId}:admin:2026-10`, competenceDate: new Date("2026-10-01") } }, update: { amount: "30000", status: "ACTIVE", updatedById: input.userId }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, economicIdentityKey: `${input.organizationId}:${input.companyId}:admin:2026-10`, provisionType: "ADMINISTRATIVE_COST", competenceDate: new Date("2026-10-01"), amount: "30000", method: "KNOWN_COST_WITHOUT_DOCUMENT", confidence: "HIGH", evidence: { source: "AdministrativeCostPlan 9F" }, policyVersion: "COST_RECOGNITION:v1", status: "ACTIVE", createdById: input.userId, updatedById: input.userId } });

  const pool = await prisma.inventoryCostPool.upsert({ where: { organizationId_projectId_code: { organizationId: input.organizationId, projectId: input.projectId, code: "OBRA-2026-10" } }, update: { totalAmount: input.measurementAmount, policyVersion: "INVENTORY:v1" }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, code: "OBRA-2026-10", name: "Construção em andamento — outubro/2026", category: "CONSTRUCTION_IN_PROGRESS", accountingPeriodId: october.id, totalAmount: input.measurementAmount, policyVersion: "INVENTORY:v1", createdById: input.userId } });
  await prisma.inventoryCostMovement.upsert({ where: { poolId_sourceType_sourceId_movementType: { poolId: pool.id, sourceType: "MEASUREMENT", sourceId: input.measurementId, movementType: "INPUT" } }, update: { amount: input.measurementAmount, eventId: measurementEvent.id, entryId: measurementEntry.id }, create: { poolId: pool.id, eventId: measurementEvent.id, entryId: measurementEntry.id, movementType: "INPUT", occurredAt: new Date("2026-10-01"), competenceDate: new Date("2026-10-01"), amount: input.measurementAmount, sourceType: "MEASUREMENT", sourceId: input.measurementId, memo: "Custo apropriável conforme política v1", createdById: input.userId } });
  const unitAllocations = allocateExact(input.measurementAmount, input.salesUnits.map((unit) => ({ id: unit.id, driver: unit.privateAreaM2 })));
  const allocationRun = await prisma.unitCostAllocationRun.upsert({ where: { poolId_version: { poolId: pool.id, version: 1 } }, update: { sourceAmount: input.measurementAmount, allocatedAmount: input.measurementAmount, residualAmount: "0", proofZero: true, driverSnapshot: { units: input.salesUnits }, checksum: hash(unitAllocations) }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, poolId: pool.id, version: 1, criterion: "PRIVATE_AREA", driverSnapshot: { units: input.salesUnits }, sourceAmount: input.measurementAmount, allocatedAmount: input.measurementAmount, residualAmount: "0", proofZero: true, status: "APPROVED", checksum: hash(unitAllocations), approvedById: input.userId, createdById: input.userId } });
  for (const line of unitAllocations) {
    const unit = input.salesUnits.find((item) => item.id === line.id)!;
    await prisma.unitCostAllocationLine.upsert({ where: { runId_salesUnitId: { runId: allocationRun.id, salesUnitId: unit.id } }, update: { driverValue: line.driver, allocationRate: line.rate, allocatedAmount: line.amount, memory: { criterion: "PRIVATE_AREA", unitCode: unit.code } }, create: { runId: allocationRun.id, salesUnitId: unit.id, unitCode: unit.code, driverValue: line.driver, allocationRate: line.rate, allocatedAmount: line.amount, memory: { criterion: "PRIVATE_AREA", unitCode: unit.code } } });
  }

  const soldUnit = input.salesUnits[0];
  const soldUnitCost = unitAllocations.find((item) => item.id === soldUnit.id)!.amount;
  const recognized = calculateRevenueRecognition({ vgv: input.soldPrice, receivable: input.soldPrice, cashReceived: "61000", recognitionRate: "0.25", allocatedUnitCost: soldUnitCost });
  const revenueRun = await prisma.revenueRecognitionRun.upsert({ where: { organizationId_projectId_cutoffDate_version: { organizationId: input.organizationId, projectId: input.projectId, cutoffDate: new Date("2026-10-31"), version: 1 } }, update: { totalVgv: "83000000", totalReceivable: recognized.receivable, totalCash: recognized.cashReceived, recognizedRevenue: recognized.recognizedRevenue, recognizedCost: recognized.recognizedCost, checksum: hash(recognized) }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, policyId: revenuePolicy.id, cutoffDate: new Date("2026-10-31"), version: 1, status: "REVIEWED", totalVgv: "83000000", totalReceivable: recognized.receivable, totalCash: recognized.cashReceived, recognizedRevenue: recognized.recognizedRevenue, recognizedCost: recognized.recognizedCost, checksum: hash(recognized), createdById: input.userId } });
  await prisma.revenueRecognitionLine.upsert({ where: { runId_salesContractId: { runId: revenueRun.id, salesContractId: input.salesContractId } }, update: { vgv: recognized.vgv, receivable: recognized.receivable, cashReceived: recognized.cashReceived, revenueRecognized: recognized.recognizedRevenue, costRecognized: recognized.recognizedCost, margin: recognized.margin, recognitionBasis: { policy: "REVENUE_RECOGNITION:v1", rate: "0.25" } }, create: { runId: revenueRun.id, salesContractId: input.salesContractId, salesUnitId: soldUnit.id, vgv: recognized.vgv, receivable: recognized.receivable, cashReceived: recognized.cashReceived, revenueRecognized: recognized.recognizedRevenue, costRecognized: recognized.recognizedCost, margin: recognized.margin, recognitionBasis: { policy: "REVENUE_RECOGNITION:v1", rate: "0.25" } } });
  const revenueEvent = await event({ key: `9G:revenue:${input.salesContractId}:1`, mappingId: revenueMapping.id, policyId: revenuePolicy.id, sourceModule: "SALES", sourceType: "SALES_CONTRACT", sourceId: input.salesContractId, eventType: "REVENUE_RECOGNITION", amount: recognized.recognizedRevenue, status: "POSTED", competenceDate: new Date("2026-10-01"), economicKey: `${input.organizationId}:${input.companyId}:sale:${input.saleId}` });
  await entry(revenueEvent.id, "202610-000003", "Receita reconhecida conforme política versionada", "1.2", "4", recognized.recognizedRevenue);
  const costEvent = await event({ key: `9G:cogs:${soldUnit.id}:1`, mappingId: cogsMapping.id, policyId: inventoryPolicy.id, sourceModule: "SALES", sourceType: "SALES_UNIT", sourceId: soldUnit.id, eventType: "INVENTORY_WRITE_OFF", amount: recognized.recognizedCost, status: "POSTED", competenceDate: new Date("2026-10-01"), economicKey: `${input.organizationId}:${input.companyId}:sale:${input.saleId}` });
  await entry(costEvent.id, "202610-000004", "Custo da unidade baixado proporcionalmente à receita reconhecida", "5.2", "1.3", recognized.recognizedCost);

  let regime = await prisma.taxRegimeAssignment.findFirst({ where: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, effectiveFrom: new Date("2026-01-01") } });
  regime ??= await prisma.taxRegimeAssignment.create({ data: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, regime: "RET", effectiveFrom: new Date("2026-01-01"), parameters: { demonstrationOnly: true, professionalValidationRequired: true }, evidence: { source: "Configuração demonstrativa 9G" }, approvedById: input.userId, createdById: input.userId } });
  const taxPolicy = await prisma.taxPolicy.upsert({ where: { assignmentId_taxCode_version: { assignmentId: regime.id, taxCode: "RET_DEMO", version: 1 } }, update: { parameters: { rate: "0.04", demonstrationOnly: true }, approvedById: input.userId }, create: { organizationId: input.organizationId, assignmentId: regime.id, taxCode: "RET_DEMO", name: "RET demonstrativo configurável", version: 1, jurisdiction: "BR", effectiveFrom: new Date("2026-01-01"), parameters: { rate: "0.04", demonstrationOnly: true }, normativeSource: "Configuração sujeita à validação profissional; não representa regra universal.", approvedById: input.userId, createdById: input.userId } });
  const taxAmount = calculateConfiguredTax({ taxableBase: recognized.recognizedRevenue, rate: "0.04" });
  const taxAssessment = await prisma.taxAssessment.upsert({ where: { organizationId_companyId_referenceMonth_taxCode_version: { organizationId: input.organizationId, companyId: input.companyId, referenceMonth: new Date("2026-10-01"), taxCode: "RET_DEMO", version: 1 } }, update: { taxableBase: recognized.recognizedRevenue, assessedAmount: taxAmount, status: "REVIEWED", checksum: hash({ base: recognized.recognizedRevenue, rate: "0.04" }) }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, policyId: taxPolicy.id, referenceMonth: new Date("2026-10-01"), version: 1, status: "REVIEWED", taxCode: "RET_DEMO", taxableBase: recognized.recognizedRevenue, assessedAmount: taxAmount, dueAt: new Date("2026-11-20"), checksum: hash({ base: recognized.recognizedRevenue, rate: "0.04" }), createdById: input.userId } });
  await prisma.taxAssessmentLine.upsert({ where: { assessmentId_sourceType_sourceId: { assessmentId: taxAssessment.id, sourceType: "REVENUE_RECOGNITION_RUN", sourceId: revenueRun.id } }, update: { taxableBase: recognized.recognizedRevenue, rate: "0.04", assessedAmount: taxAmount, memory: { configuredPolicy: taxPolicy.id } }, create: { assessmentId: taxAssessment.id, sourceType: "REVENUE_RECOGNITION_RUN", sourceId: revenueRun.id, taxableBase: recognized.recognizedRevenue, rate: "0.04", assessedAmount: taxAmount, memory: { configuredPolicy: taxPolicy.id } } });
  await prisma.fiscalDocumentReference.upsert({ where: { organizationId_documentId: { organizationId: input.organizationId, documentId: input.measurementId } }, update: { companyId: input.companyId, projectId: input.projectId, amount: input.measurementAmount, checksum: hash(input.measurementId) }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, documentId: input.measurementId, documentType: "MEASUREMENT_EVIDENCE", issuedAt: new Date("2026-10-01"), amount: input.measurementAmount, checksum: hash(input.measurementId), createdById: input.userId } });

  const allocation = allocateExact("100000", [{ id: input.holdingCompanyId, driver: 0.4 }, { id: input.companyId, driver: 0.6 }]);
  const allocationControl = await prisma.accountingAllocationRun.upsert({ where: { organizationId_sourceType_sourceId_referenceMonth: { organizationId: input.organizationId, sourceType: "ADMINISTRATIVE_COST_PLAN", sourceId: "PLAN-9F-DEMO", referenceMonth: new Date("2026-10-01") } }, update: { allocatedAmount: "100000", residualAmount: "0", proofZero: true, driverSnapshot: { allocation }, checksum: hash(allocation) }, create: { organizationId: input.organizationId, companyId: input.holdingCompanyId, referenceMonth: new Date("2026-10-01"), sourceType: "ADMINISTRATIVE_COST_PLAN", sourceId: "PLAN-9F-DEMO", driver: "DIRECT_COST", driverSnapshot: { allocation }, sourceAmount: "100000", allocatedAmount: "100000", residualAmount: "0", proofZero: true, status: "APPROVED", checksum: hash(allocation), createdById: input.userId, approvedById: input.userId } });
  for (const line of allocation) {
    const targetProjectId = line.id === input.companyId ? input.projectId : null;
    const existingLine = await prisma.accountingAllocationLine.findFirst({ where: { runId: allocationControl.id, targetCompanyId: line.id, targetProjectId } });
    if (existingLine) await prisma.accountingAllocationLine.update({ where: { id: existingLine.id }, data: { driverValue: line.driver, allocationRate: line.rate, allocatedAmount: line.amount } });
    else await prisma.accountingAllocationLine.create({ data: { runId: allocationControl.id, targetCompanyId: line.id, targetProjectId, driverValue: line.driver, allocationRate: line.rate, allocatedAmount: line.amount } });
  }

  await prisma.accountingReconciliation.upsert({ where: { periodId_reconciliationType_projectId: { periodId: october.id, reconciliationType: "AP_VS_LEDGER", projectId: input.projectId } }, update: { status: "DIVERGENT", sourceAmount: "200000", ledgerAmount: "197000", differenceAmount: "3000", material: true, evidence: { payableId: input.payableId, action: "Revisar classificação; nenhum ajuste automático." } }, create: { organizationId: input.organizationId, companyId: input.companyId, projectId: input.projectId, periodId: october.id, reconciliationType: "AP_VS_LEDGER", status: "DIVERGENT", sourceAmount: "200000", ledgerAmount: "197000", differenceAmount: "3000", material: true, evidence: { payableId: input.payableId, action: "Revisar classificação; nenhum ajuste automático." }, createdById: input.userId, items: { create: [{ sourceType: "PAYABLE_ACCOUNT", sourceId: input.payableId, ledgerEntryId: measurementEntry.id, sourceAmount: "200000", ledgerAmount: "197000", differenceAmount: "3000", notes: "Divergência demonstrativa, sem ajuste silencioso." }] } } });

  const scope = await prisma.consolidationScope.upsert({ where: { organizationId_economicGroupId_name_version: { organizationId: input.organizationId, economicGroupId: input.economicGroupId, name: "Consolidação REDE — Demonstração", version: 1 } }, update: { companies: [{ companyId: input.holdingCompanyId, participation: "1" }, { companyId: input.companyId, participation: "1" }], approvedById: input.userId }, create: { organizationId: input.organizationId, economicGroupId: input.economicGroupId, name: "Consolidação REDE — Demonstração", version: 1, effectiveFrom: new Date("2026-01-01"), companies: [{ companyId: input.holdingCompanyId, participation: "1" }, { companyId: input.companyId, participation: "1" }], method: "FULL", createdById: input.userId, approvedById: input.userId } });
  const consolidated = calculateConsolidation({ individualAmount: "4000000", eliminationAmount: input.intercompanyAmount });
  const consolidation = await prisma.consolidationRun.upsert({ where: { scopeId_referenceMonth_version: { scopeId: scope.id, referenceMonth: new Date("2026-10-01"), version: 1 } }, update: { status: "REVIEWED", individualAmount: consolidated.individual, adjustmentAmount: consolidated.adjustment, eliminationAmount: consolidated.elimination, consolidatedAmount: consolidated.consolidated, proofZero: consolidated.proofZero, checksum: hash(consolidated) }, create: { organizationId: input.organizationId, economicGroupId: input.economicGroupId, scopeId: scope.id, referenceMonth: new Date("2026-10-01"), version: 1, status: "REVIEWED", individualAmount: consolidated.individual, adjustmentAmount: consolidated.adjustment, eliminationAmount: consolidated.elimination, consolidatedAmount: consolidated.consolidated, proofZero: consolidated.proofZero, checksum: hash(consolidated), createdById: input.userId } });
  await prisma.consolidationElimination.upsert({ where: { runId_sourceType_sourceId: { runId: consolidation.id, sourceType: "INTERCOMPANY_TRANSACTION", sourceId: input.intercompanyId } }, update: { amount: input.intercompanyAmount, justification: "Eliminação de direito e obrigação recíprocos sem criar exposição econômica artificial.", evidence: { intercompanyId: input.intercompanyId }, approvedById: input.userId }, create: { runId: consolidation.id, fromCompanyId: input.holdingCompanyId, toCompanyId: input.companyId, sourceType: "INTERCOMPANY_TRANSACTION", sourceId: input.intercompanyId, amount: input.intercompanyAmount, justification: "Eliminação de direito e obrigação recíprocos sem criar exposição econômica artificial.", evidence: { intercompanyId: input.intercompanyId }, approvedById: input.userId, createdById: input.userId } });
  await prisma.consolidatedBalanceSnapshot.upsert({ where: { runId: consolidation.id }, update: { balances: { individual: consolidated.individual, eliminations: consolidated.elimination, consolidated: consolidated.consolidated }, statements: { demonstration: true }, checksum: hash(consolidated), createdById: input.userId }, create: { runId: consolidation.id, balances: { individual: consolidated.individual, eliminations: consolidated.elimination, consolidated: consolidated.consolidated }, statements: { demonstration: true }, checksum: hash(consolidated), createdById: input.userId } });

  return { chart, chartVersion, october, measurementEntry, pool, allocationRun, revenueRun, taxAssessment, consolidation };
}
