import Decimal from "decimal.js";
import type { MembershipRole } from "@prisma/client";
import { calculateProject } from "@/domain/financial/engine";
import type { ProjectAssumptions, ScenarioKey } from "@/domain/financial/types";
import { calculateRedeScore } from "@/domain/score";
import { calculateSensitivity } from "@/domain/sensitivity";
import { analyzeRisk } from "@/domain/risk/rules";
import { solveReverseZoning } from "@/domain/land/solver";
import { calculateCriticalPath, calculateDelayStress, calculateLandValueCeiling } from "@/domain/investment/transformation";
import type { AIResponseEvidenceInput, AIToolCallResult, AIToolDefinition, RelevantContextPackage } from "@/domain/ai";
import { compareScenarioArgumentsSchema, contextChangeSchema, delayArgumentsSchema, emptyArgumentsSchema, reverseZoningArgumentsSchema, scenarioArgumentsSchema, searchArgumentsSchema, simulationArgumentsSchema } from "@/domain/ai";
import { preflightMasterReport } from "@/application/investment/studio-service";
import { createDecisionSandbox } from "@/application/investment/investment-service";
import { prisma } from "@/infrastructure/database/prisma";
import { persistContextSelection } from "./context-builder";
import { searchInternalEvidence } from "./retrieval";
import { compareDesignMetrics, type DesignConfidence } from "@/domain/design";
import { getOperationsWorkspace } from "@/application/operations/operations-service";
import { getFinancialWorkspace } from "@/application/financial-ops/financial-service";
import { getProcurementWorkspace } from "@/application/procurement/procurement-service";
import { getLegalWorkspace } from "@/application/legal/legal-service";
import { getSalesWorkspace } from "@/application/sales/sales-service";
import { getPeoplePerformanceWorkspace } from "@/application/people-performance/people-performance-service";
import { getAccountingWorkspace } from "@/application/accounting/accounting-service";
import { getIntegrationsWorkspace } from "@/application/integrations/integrations-service";

const roleRank: Record<MembershipRole, number> = { VIEWER: 0, REVIEWER: 1, ANALYST: 2, ADMIN: 3, OWNER: 4 };
const jsonClone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

function evidence(input: Omit<AIResponseEvidenceInput, "statementId" | "confidence"> & { statementId?: string; confidence?: AIResponseEvidenceInput["confidence"] }): AIResponseEvidenceInput {
  return { statementId: input.statementId ?? input.evidenceRef.replace(/[^A-Za-z0-9]+/g, "-").slice(0, 80), confidence: input.confidence ?? "HIGH", ...input };
}

function makeTool(input: Omit<AIToolDefinition, "validate"> & { schema?: { parse(value: unknown): unknown } }): AIToolDefinition {
  return { ...input, validate: (arguments_) => (input.schema ?? emptyArgumentsSchema).parse(arguments_) as Record<string, unknown> };
}

function scenarioOf(context: RelevantContextPackage, args: Record<string, unknown>): ScenarioKey {
  return (args.scenario as ScenarioKey | undefined) ?? context.selection.financialScenario;
}

function engineEvidence(context: RelevantContextPackage, scenario: ScenarioKey, field: string, value?: string): AIResponseEvidenceInput {
  return evidence({ sourceType: "ENGINE", entityType: "StudyVersion", entityId: context.workspace.bundle.studyVersionId, field, version: `v${context.workspace.bundle.studyVersionNumber}`, scenario, evidenceRef: `engine:${context.workspace.bundle.studyVersionId}:${scenario}:${field}`, label: `Engine · v${context.workspace.bundle.studyVersionNumber} · ${scenario}`, value });
}

const aiDesignConfidence = (value: DesignConfidence): AIResponseEvidenceInput["confidence"] => value === "NOT_VERIFIED" ? "NOT_AVAILABLE" : value;

function applySimulationChanges(base: ProjectAssumptions, raw: Record<string, number>): ProjectAssumptions {
  const next = { ...base };
  if (raw.unitPricePercent !== undefined) next.unitPrice = new Decimal(base.unitPrice).mul(new Decimal(1).plus(new Decimal(raw.unitPricePercent).div(100))).toFixed(2);
  if (raw.constructionCostPercent !== undefined) next.constructionCostPerM2 = new Decimal(base.constructionCostPerM2).mul(new Decimal(1).plus(new Decimal(raw.constructionCostPercent).div(100))).toFixed(2);
  if (raw.landPriceDelta !== undefined) next.landPrice = Decimal.max(0, new Decimal(base.landPrice).plus(raw.landPriceDelta)).toFixed(2);
  if (raw.approvalMonthsDelta !== undefined) next.approvalMonths = Math.max(0, base.approvalMonths + raw.approvalMonthsDelta);
  if (raw.salesVelocityPercent !== undefined) next.salesVelocityUnitsMonth = Decimal.max(0.01, new Decimal(base.salesVelocityUnitsMonth).mul(new Decimal(1).plus(new Decimal(raw.salesVelocityPercent).div(100)))).toFixed(4);
  if (raw.financingRateDeltaPp !== undefined) next.annualFinancingRate = Decimal.max(0, new Decimal(base.annualFinancingRate).plus(raw.financingRateDeltaPp)).toFixed(4);
  if (raw.units !== undefined) next.units = raw.units;
  return next;
}

async function changeContext(context: RelevantContextPackage, args: Record<string, unknown>): Promise<AIToolCallResult> {
  const requested = contextChangeSchema.parse(args);
  const selection = { ...context.selection };
  if (requested.financialScenario) selection.financialScenario = requested.financialScenario;
  if (requested.latestVersion) {
    const latest = await prisma.investmentSnapshotBundle.findFirst({ where: { investmentCaseId: context.workspace.id, investmentCase: { organizationId: context.organizationId } }, orderBy: { version: "desc" }, select: { id: true, content: true } });
    if (!latest) throw new Error("O Investment Case ainda não possui snapshot disponível.");
    const content = latest.content as unknown as typeof context.workspace.bundle;
    selection.studyVersionId = content.studyVersionId;
    selection.studyVersionNumber = content.studyVersionNumber;
    selection.snapshotBundleId = latest.id;
    selection.financialScenario = content.scenario;
    const selectedUrban = content.land?.scenarios.find((item) => item.id === content.land?.selectedScenarioId);
    selection.urbanScenarioId = selectedUrban?.id ?? null;
    selection.urbanScenarioType = selectedUrban?.type ?? null;
  }
  if (requested.studyVersionNumber && requested.studyVersionNumber !== selection.studyVersionNumber) {
    const rows = await prisma.investmentSnapshotBundle.findMany({ where: { investmentCaseId: context.workspace.id, investmentCase: { organizationId: context.organizationId } }, select: { id: true, content: true } });
    const bundle = rows.find((row) => (row.content as { studyVersionNumber?: number }).studyVersionNumber === requested.studyVersionNumber);
    if (!bundle) throw new Error(`A versão v${requested.studyVersionNumber} não possui snapshot neste Investment Case.`);
    const content = bundle.content as unknown as typeof context.workspace.bundle;
    selection.studyVersionId = content.studyVersionId;
    selection.studyVersionNumber = content.studyVersionNumber;
    selection.snapshotBundleId = bundle.id;
  }
  if (requested.urbanScenarioType) {
    const urban = context.workspace.bundle.land?.scenarios.find((item) => item.type === requested.urbanScenarioType);
    if (!urban) throw new Error(`O cenário urbanístico ${requested.urbanScenarioType} não está disponível no snapshot atual.`);
    selection.urbanScenarioId = urban.id;
    selection.urbanScenarioType = urban.type;
  }
  await persistContextSelection(context.organizationId, context.conversationId, selection);
  return { name: "changeContext", mode: "READ_ONLY", status: "COMPLETED", data: selection };
}

export class AIToolRegistry {
  private readonly tools = new Map<string, AIToolDefinition>();
  constructor() { for (const tool of createTools()) this.tools.set(tool.name, tool); }
  list() { return [...this.tools.values()].map(({ name, description, mode, minimumRole }) => ({ name, description, mode, minimumRole })); }
  get(name: string) { return this.tools.get(name); }
  async execute(context: RelevantContextPackage, name: string, rawArguments: Record<string, unknown>): Promise<AIToolCallResult> {
    const tool = this.tools.get(name);
    if (!tool) throw new Error(`Ferramenta não autorizada: ${name}`);
    if (roleRank[context.role] < roleRank[tool.minimumRole]) throw new Error("Seu perfil não possui permissão para esta ferramenta.");
    if (tool.mode === "SIMULATION" && !context.permissions.canSimulate) throw new Error("Seu perfil não pode executar simulações.");
    if (tool.mode === "MUTATION" && !context.permissions.canMutate) throw new Error("Seu perfil não pode executar esta ação.");
    const arguments_ = tool.validate(rawArguments);
    return tool.execute(context, arguments_);
  }
}

function createTools(): AIToolDefinition[] {
  const read = "VIEWER" as MembershipRole;
  const simulate = "ANALYST" as MembershipRole;
  return [
    makeTool({ name: "getProject", description: "Consulta o empreendimento ativo.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getProject", mode: "READ_ONLY", status: "COMPLETED", data: { ...c.workspace.bundle.project, assumptions: { units: c.workspace.bundle.assumptions.units, landAreaM2: c.workspace.bundle.assumptions.landAreaM2, privateAreaPerUnitM2: c.workspace.bundle.assumptions.privateAreaPerUnitM2 } }, evidence: [evidence({ sourceType: "USER_INPUT", entityType: "Project", entityId: c.workspace.bundle.projectId, version: `v${c.workspace.bundle.studyVersionNumber}`, evidenceRef: `project:${c.workspace.bundle.projectId}`, label: `Projeto · Snapshot v${c.workspace.bundle.studyVersionNumber}` })] }; } }),
    makeTool({ name: "getStudy", description: "Consulta o estudo ativo.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getStudy", mode: "READ_ONLY", status: "COMPLETED", data: { studyId: c.workspace.bundle.studyId, projectId: c.workspace.bundle.projectId } }; } }),
    makeTool({ name: "getStudyVersion", description: "Consulta a versão selecionada.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getStudyVersion", mode: "READ_ONLY", status: "COMPLETED", data: { id: c.workspace.bundle.studyVersionId, number: c.workspace.bundle.studyVersionNumber, frozenAt: c.workspace.bundle.frozenAt, checksum: c.workspace.bundleChecksum } }; } }),
    makeTool({ name: "getAssumptions", description: "Consulta premissas e confidence.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getAssumptions", mode: "READ_ONLY", status: "COMPLETED", data: { values: c.workspace.bundle.assumptions, register: c.workspace.assumptionsRegister }, evidence: c.workspace.assumptionsRegister.map((item) => evidence({ sourceType: "USER_INPUT", entityType: "AssumptionRegisterItem", entityId: item.id, field: item.key, version: item.sourceVersion, evidenceRef: item.evidenceRef, confidence: item.status === "VALIDATED" ? "HIGH" : "MEDIUM", label: `${item.key} · ${item.sourceVersion}`, value: item.value })) }; } }),
    makeTool({ name: "getEngineResults", description: "Consulta métricas determinísticas do Engine.", mode: "READ_ONLY", minimumRole: read, schema: scenarioArgumentsSchema, async execute(c, a) { const s = scenarioOf(c, a); const result = c.workspace.bundle.engineResults[s]; const fields = ["vgv", "marginOnVgv", "profit", "roi", "annualIrr", "npv", "maximumCashExposure", "equityCapitalRequired"] as const; return { name: "getEngineResults", mode: "READ_ONLY", status: "COMPLETED", data: { scenario: s, metrics: result.metrics, recommendation: analyzeRisk(result) }, evidence: fields.map((field) => engineEvidence(c, s, field, String(result.metrics[field] ?? "N/D"))) }; } }),
    makeTool({ name: "getCashFlow", description: "Consulta fluxo mensal do Engine.", mode: "READ_ONLY", minimumRole: read, schema: scenarioArgumentsSchema, async execute(c, a) { const s = scenarioOf(c, a); const flow = c.workspace.bundle.engineResults[s].cashFlow; return { name: "getCashFlow", mode: "READ_ONLY", status: "COMPLETED", data: { scenario: s, months: flow, criticalMonth: c.workspace.bundle.engineResults[s].metrics.maximumExposureMonth }, evidence: [engineEvidence(c, s, "cashFlow")] }; } }),
    makeTool({ name: "getOperationalBaseline", description: "Consulta a Base Aprovada imutável e sua origem.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const operations = await getOperationsWorkspace(c, c.workspace.bundle.projectId); return { name: "getOperationalBaseline", mode: "READ_ONLY", status: "COMPLETED", data: operations.baseline ?? { unavailable: true }, evidence: operations.baseline ? [evidence({ sourceType: "OTHER", entityType: "OperationalBaseline", entityId: operations.baseline.id, version: `v${operations.baseline.version}`, evidenceRef: `operations:baseline:${operations.baseline.id}`, label: `Base Aprovada · v${operations.baseline.version}`, value: String(operations.baseline.total) })] : [] }; } }),
    makeTool({ name: "getOfficialBudget", description: "Consulta o Orçamento Oficial vigente e rastreável.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const operations = await getOperationsWorkspace(c, c.workspace.bundle.projectId); return { name: "getOfficialBudget", mode: "READ_ONLY", status: "COMPLETED", data: operations.budget ?? { unavailable: true }, evidence: operations.budget ? [evidence({ sourceType: "OTHER", entityType: "Budget", entityId: operations.budget.id, version: `v${operations.budget.version}`, evidenceRef: `operations:budget:${operations.budget.id}`, label: `Orçamento Oficial · v${operations.budget.version}`, value: String(operations.budget.total) })] : [] }; } }),
    makeTool({ name: "compareBaselineToBudget", description: "Calcula a ponte Base Aprovada × Orçamento Oficial e os maiores desvios.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const operations = await getOperationsWorkspace(c, c.workspace.bundle.projectId); return { name: "compareBaselineToBudget", mode: "READ_ONLY", status: "COMPLETED", data: { rows: [...operations.bridge].sort((a, b) => Math.abs(b.difference) - Math.abs(a.difference)), baselineTotal: operations.baseline?.total ?? 0, budgetTotal: operations.budget?.total ?? 0 }, evidence: operations.baseline && operations.budget ? [evidence({ sourceType: "OTHER", entityType: "BudgetBridge", entityId: operations.budget.id, version: `Base v${operations.baseline.version} × Orçamento v${operations.budget.version}`, evidenceRef: `operations:bridge:${operations.baseline.id}:${operations.budget.id}`, label: "Ponte do Orçamento" })] : [] }; } }),
    makeTool({ name: "getOperationalSchedule", description: "Consulta cronograma, duração, atividades e prova-zero.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const operations = await getOperationsWorkspace(c, c.workspace.bundle.projectId); return { name: "getOperationalSchedule", mode: "READ_ONLY", status: "COMPLETED", data: { schedule: operations.schedule, indicators: operations.indicators }, evidence: operations.schedule ? [evidence({ sourceType: "OTHER", entityType: "OperationalSchedule", entityId: operations.schedule.id, version: `v${operations.schedule.version}`, evidenceRef: `operations:schedule:${operations.schedule.id}`, label: `Cronograma Físico-Financeiro · v${operations.schedule.version}` })] : [] }; } }),
    makeTool({ name: "getProjectedDisbursement", description: "Consulta desembolso mensal, próximos 90 dias e mês de pico.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const operations = await getOperationsWorkspace(c, c.workspace.bundle.projectId); return { name: "getProjectedDisbursement", mode: "READ_ONLY", status: "COMPLETED", data: { cashFlow: operations.cashFlow, indicators: operations.indicators }, evidence: operations.schedule ? [evidence({ sourceType: "OTHER", entityType: "ScheduleAllocation", entityId: operations.schedule.id, version: `v${operations.schedule.version}`, evidenceRef: `operations:disbursement:${operations.schedule.id}`, label: "Fluxo projetado do orçamento", value: String(operations.indicators.totalCost) })] : [] }; } }),
    makeTool({ name: "getCashPosition", description: "Consulta caixa total, livre e restrito por conta bancária.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const financial = await getFinancialWorkspace(c, c.workspace.bundle.projectId); return { name: "getCashPosition", mode: "READ_ONLY", status: "COMPLETED", data: { cashPosition: financial.cashPosition, bankAccounts: financial.bankAccounts, capitalNeed: financial.capitalNeed }, evidence: [evidence({ sourceType: "OTHER", entityType: "BankAccount", entityId: financial.projectId, evidenceRef: `financial:cash:${financial.projectId}`, label: "Posição de caixa consolidada", value: String(financial.cashPosition.total) })] }; } }),
    makeTool({ name: "getPayablesDue", description: "Consulta contas a pagar em aberto, vencidas e por horizonte de vencimento.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const financial = await getFinancialWorkspace(c, c.workspace.bundle.projectId); return { name: "getPayablesDue", mode: "READ_ONLY", status: "COMPLETED", data: financial.payables, evidence: [evidence({ sourceType: "OTHER", entityType: "PayableAccount", entityId: financial.projectId, evidenceRef: `financial:payables:${financial.projectId}`, label: "Contas a pagar em aberto", value: String(financial.payables.totalOpen) })] }; } }),
    makeTool({ name: "getReceivablesDue", description: "Consulta contas a receber em aberto, vencidas e por horizonte de vencimento.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const financial = await getFinancialWorkspace(c, c.workspace.bundle.projectId); return { name: "getReceivablesDue", mode: "READ_ONLY", status: "COMPLETED", data: financial.receivables, evidence: [evidence({ sourceType: "OTHER", entityType: "ReceivableAccount", entityId: financial.projectId, evidenceRef: `financial:receivables:${financial.projectId}`, label: "Contas a receber em aberto", value: String(financial.receivables.totalOpen) })] }; } }),
    makeTool({ name: "getUpdatedCashProjection", description: "Consulta projeção atualizada (realizado + compromisso concreto + previsão residual) sem dupla contagem.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const financial = await getFinancialWorkspace(c, c.workspace.bundle.projectId); return { name: "getUpdatedCashProjection", mode: "READ_ONLY", status: "COMPLETED", data: { rows: financial.updatedProjection, capitalNeed: financial.capitalNeed }, evidence: [evidence({ sourceType: "OTHER", entityType: "ProjectedCashFlow", entityId: financial.projectId, evidenceRef: `financial:projection:${financial.projectId}`, label: "Projeção Atualizada" })] }; } }),
    makeTool({ name: "getReconciliationStatus", description: "Consulta pendências de conciliação bancária e intercompany.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const financial = await getFinancialWorkspace(c, c.workspace.bundle.projectId); return { name: "getReconciliationStatus", mode: "READ_ONLY", status: "COMPLETED", data: { pendingReconciliations: financial.pendingReconciliations, pendingIntercompany: financial.pendingIntercompany } }; } }),
    makeTool({ name: "getProcurementStages", description: "Consulta Orçamento, Contratado, Medido, Obrigado, Pago e saldos sem dupla contagem.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const workspace = await getProcurementWorkspace(c, c.workspace.bundle.projectId); return { name: "getProcurementStages", mode: "READ_ONLY", status: "COMPLETED", data: workspace.summary, evidence: [evidence({ sourceType: "OTHER", entityType: "ProcurementStageLedger", entityId: workspace.projectId, evidenceRef: `procurement:stages:${workspace.projectId}`, label: "Cadeia econômica de suprimentos", value: String(workspace.summary.contracted) })] }; } }),
    makeTool({ name: "getCriticalPurchases", description: "Lista compras cuja data-limite de contratação ameaça o cronograma.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const workspace = await getProcurementWorkspace(c, c.workspace.bundle.projectId); return { name: "getCriticalPurchases", mode: "READ_ONLY", status: "COMPLETED", data: workspace.needs.filter((item) => item.critical), evidence: [evidence({ sourceType: "OTHER", entityType: "ProcurementNeed", entityId: workspace.projectId, evidenceRef: `procurement:critical:${workspace.projectId}`, label: "Plano de suprimentos", value: String(workspace.summary.criticalPurchases) })] }; } }),
    makeTool({ name: "getContractsAndAmendments", description: "Consulta contratos, aditivos, valor atual, medido e saldo.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const workspace = await getProcurementWorkspace(c, c.workspace.bundle.projectId); return { name: "getContractsAndAmendments", mode: "READ_ONLY", status: "COMPLETED", data: workspace.contracts, evidence: workspace.contracts.map((contract) => evidence({ sourceType: "OTHER", entityType: "OperationalContract", entityId: contract.id, evidenceRef: `procurement:contract:${contract.id}`, label: `${contract.number} · ${contract.title}`, value: String(contract.currentAmount) })) }; } }),
    makeTool({ name: "getValidatedSaving", description: "Consulta economia validada e sua proveniência de cotação.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const workspace = await getProcurementWorkspace(c, c.workspace.bundle.projectId); return { name: "getValidatedSaving", mode: "READ_ONLY", status: "COMPLETED", data: { validatedSaving: workspace.summary.validatedSaving, quotations: workspace.quotations.filter((item) => item.selectedProposalId) }, evidence: [evidence({ sourceType: "OTHER", entityType: "ValidatedSaving", entityId: workspace.projectId, evidenceRef: `procurement:saving:${workspace.projectId}`, label: "Economia validada", value: String(workspace.summary.validatedSaving) })] }; } }),
    makeTool({ name: "getLegalReadiness", description: "Consulta prontidão jurídica, bloqueios, documentos e achados críticos.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const workspace = await getLegalWorkspace(c, c.workspace.bundle.projectId); return { name: "getLegalReadiness", mode: "READ_ONLY", status: "COMPLETED", data: workspace.summary, evidence: [evidence({ sourceType: "OTHER", entityType: "LegalDueDiligenceCase", entityId: workspace.projectId, evidenceRef: `legal:readiness:${workspace.projectId}`, label: "Prontidão jurídica", value: String(workspace.summary.readiness.score) })] }; } }),
    makeTool({ name: "getLegalDeadlines", description: "Lista obrigações, licenças, alertas e marcos jurídicos que afetam o cronograma.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const workspace = await getLegalWorkspace(c, c.workspace.bundle.projectId); return { name: "getLegalDeadlines", mode: "READ_ONLY", status: "COMPLETED", data: { obligations: workspace.obligations, licenses: workspace.licenses, alerts: workspace.alerts, timeline: workspace.timeline }, evidence: workspace.alerts.map((item) => evidence({ sourceType: "OTHER", entityType: "LegalAlert", entityId: item.id, evidenceRef: `legal:alert:${item.id}`, label: item.title })) }; } }),
    makeTool({ name: "getPropertyDueDiligence", description: "Consulta matrícula, IPTU, cadastro municipal, partes, documentos e parecer da diligência imobiliária.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const workspace = await getLegalWorkspace(c, c.workspace.bundle.projectId); return { name: "getPropertyDueDiligence", mode: "READ_ONLY", status: "COMPLETED", data: { cases: workspace.cases, registrations: workspace.registrations, municipalRecords: workspace.municipalRecords, landContracts: workspace.contracts }, evidence: workspace.registrations.map((item) => evidence({ sourceType: "DOCUMENT", entityType: "LegalAssetRegistration", entityId: item.id, version: `v${item.version}`, evidenceRef: `legal:registration:${item.id}`, label: `Matrícula ${item.registrationNumber}` })) }; } }),
    makeTool({ name: "getPendingMeasurements", description: "Lista medições aguardando análise ou aprovação.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const workspace = await getProcurementWorkspace(c, c.workspace.bundle.projectId); return { name: "getPendingMeasurements", mode: "READ_ONLY", status: "COMPLETED", data: workspace.measurements.filter((item) => !["SENT_TO_FINANCE", "REVERSED", "CANCELLED"].includes(item.status)) }; } }),
    makeTool({ name: "getSalesInventory", description: "Consulta quantas unidades estão disponíveis, reservadas, vendidas e o VGV por estágio.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); return { name: "getSalesInventory", mode: "READ_ONLY", status: "COMPLETED", data: { summary: sales.summary, units: sales.units }, evidence: [evidence({ sourceType: "OTHER", entityType: "SalesUnit", entityId: sales.projectId, evidenceRef: `sales:inventory:${sales.projectId}`, label: "Estoque comercial", value: String(sales.summary.unitsAvailable) })] }; } }),
    makeTool({ name: "getUnitTypologyPerformance", description: "Consulta qual tipologia vende mais e a preço médio por m².", mode: "READ_ONLY", minimumRole: read, async execute(c) { const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); const byTypology = new Map<string, { sold: number; totalArea: number; totalValue: number }>(); for (const unit of sales.units) { if (unit.status !== "VENDIDA" && unit.status !== "ENTREGUE") continue; const current = byTypology.get(unit.typology) ?? { sold: 0, totalArea: 0, totalValue: 0 }; current.sold += 1; current.totalArea += unit.privateAreaM2; current.totalValue += unit.listPrice ?? 0; byTypology.set(unit.typology, current); } return { name: "getUnitTypologyPerformance", mode: "READ_ONLY", status: "COMPLETED", data: [...byTypology.entries()].map(([typology, row]) => ({ typology, ...row })) }; } }),
    makeTool({ name: "getPricePerSquareMeter", description: "Consulta o preço/m² realizado, médio do estoque atual.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); return { name: "getPricePerSquareMeter", mode: "READ_ONLY", status: "COMPLETED", data: { averagePricePerM2: sales.summary.averagePricePerM2, byUnit: sales.units.map((unit) => ({ code: unit.code, pricePerM2: unit.pricePerM2 })) }, evidence: [evidence({ sourceType: "OTHER", entityType: "SalesUnit", entityId: sales.projectId, evidenceRef: `sales:price-per-m2:${sales.projectId}`, label: "Preço/m² médio", value: String(sales.summary.averagePricePerM2) })] }; } }),
    makeTool({ name: "getDiscountGranted", description: "Consulta quanto foi concedido em desconto nas vendas aprovadas.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); return { name: "getDiscountGranted", mode: "READ_ONLY", status: "COMPLETED", data: { averageDiscount: sales.summary.averageDiscount, sales: sales.sales.filter((item) => item.status === "APPROVED").map((item) => ({ unit: item.unit, soldPrice: item.soldPrice, discountAmount: item.discountAmount })) } }; } }),
    makeTool({ name: "getExpiringProposals", description: "Lista propostas comerciais próximas do vencimento.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); const now = Date.now(); const soon = sales.proposals.filter((item) => ["SUBMITTED", "UNDER_APPROVAL"].includes(item.status) && new Date(item.validUntil).getTime() - now <= 7 * 86_400_000); return { name: "getExpiringProposals", mode: "READ_ONLY", status: "COMPLETED", data: soon }; } }),
    makeTool({ name: "getDelinquentCustomers", description: "Consulta quais clientes de vendas estão inadimplentes, lendo diretamente o Financeiro (9B), filtrado por origem venda.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const financial = await getFinancialWorkspace(c, c.workspace.bundle.projectId); const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); const saleUnitByCustomer = new Map(sales.sales.flatMap((item) => item.buyers.map((buyer) => [buyer, item.unit] as const))); const overdue = financial.receivables.overdueItems.filter((item) => item.customer && saleUnitByCustomer.has(item.customer)); return { name: "getDelinquentCustomers", mode: "READ_ONLY", status: "COMPLETED", data: overdue, evidence: [evidence({ sourceType: "OTHER", entityType: "ReceivableInstallment", entityId: sales.projectId, evidenceRef: `financial:receivables:overdue:${sales.projectId}`, label: "Inadimplência — leitura direta da 9B", value: String(overdue.length) })] }; } }),
    makeTool({ name: "getReceivableCurve", description: "Consulta a curva de recebíveis (contratado, a receber, vencido), lida do Financeiro (9B) sem recalcular.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const financial = await getFinancialWorkspace(c, c.workspace.bundle.projectId); const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); return { name: "getReceivableCurve", mode: "READ_ONLY", status: "COMPLETED", data: { vgvVendido: sales.summary.vgvVendido, vgvRecebido: sales.summary.vgvRecebido, vgvAReceber: sales.summary.vgvAReceber, horizons: financial.receivables.horizons } }; } }),
    makeTool({ name: "getRescindedUnits", description: "Lista unidades distratadas e o histórico da venda original preservado.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); return { name: "getRescindedUnits", mode: "READ_ONLY", status: "COMPLETED", data: { units: sales.units.filter((unit) => unit.status === "DISTRATADA"), sales: sales.sales.filter((item) => item.status === "CANCELLED") } }; } }),
    makeTool({ name: "getPendingCommissions", description: "Consulta quanto se deve de comissão a corretores/imobiliárias.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); return { name: "getPendingCommissions", mode: "READ_ONLY", status: "COMPLETED", data: sales.commissions.filter((item) => item.status === "PENDING" || item.status === "APPROVED") }; } }),
    makeTool({ name: "getUnitsAwaitingDelivery", description: "Lista unidades vendidas aguardando entrega/vistoria e solicitações de pós-venda em aberto.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const sales = await getSalesWorkspace(c, c.workspace.bundle.projectId); return { name: "getUnitsAwaitingDelivery", mode: "READ_ONLY", status: "COMPLETED", data: { units: sales.units.filter((unit) => unit.status === "VENDIDA"), openPostSale: sales.postSaleRequests.filter((item) => !["RESOLVED", "CLOSED"].includes(item.status)) } }; } }),
    makeTool({ name: "getOrganizationalStructure", description: "Consulta estrutura organizacional e vínculos profissionais sem expor remuneração individual.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const people = await getPeoplePerformanceWorkspace({ organizationId: c.organizationId, role: "VIEWER" }, c.workspace.bundle.projectId); return { name: "getOrganizationalStructure", mode: "READ_ONLY", status: "COMPLETED", data: { departments: people.departments, positions: people.positions, people: people.people.map((person) => ({ id: person.id, relationshipId: person.relationshipId, name: person.name, company: person.company, department: person.department, position: person.position, relationshipType: person.relationshipType, weeklyHours: person.weeklyHours, compensationRestricted: true })), teams: people.teams }, evidence: [evidence({ sourceType: "OTHER", entityType: "PersonProfile", entityId: people.projectId, evidenceRef: `people:structure:${people.projectId}`, label: "Estrutura organizacional vigente", value: String(people.summary.people) })] }; } }),
    makeTool({ name: "getTeamCapacity", description: "Consulta equipes, capacidade e superalocações justificadas.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const people = await getPeoplePerformanceWorkspace({ organizationId: c.organizationId, role: "VIEWER" }, c.workspace.bundle.projectId); return { name: "getTeamCapacity", mode: "READ_ONLY", status: "COMPLETED", data: { teams: people.teams, allocations: people.allocations }, evidence: [evidence({ sourceType: "OTHER", entityType: "WorkAllocation", entityId: people.projectId, evidenceRef: `people:capacity:${people.projectId}`, label: "Capacidade e alocações", value: String(people.summary.allocations) })] }; } }),
    makeTool({ name: "getEfficiencyVariances", description: "Consulta métricas e desvios físico-financeiros; não classifica desembolso menor como economia.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const people = await getPeoplePerformanceWorkspace({ organizationId: c.organizationId, role: "VIEWER" }, c.workspace.bundle.projectId); return { name: "getEfficiencyVariances", mode: "READ_ONLY", status: "COMPLETED", data: { runs: people.efficiencyRuns, cases: people.varianceCases.map((item) => ({ id: item.id, code: item.code, title: item.title, type: item.type, status: item.status, plannedAmount: item.plannedAmount, actualAmount: item.actualAmount, cashVariance: item.cashVariance, commitmentVariance: item.commitmentVariance, plannedProgress: item.plannedProgress, actualProgress: item.actualProgress, savingEligible: item.savingEligible })) }, evidence: people.varianceCases.map((item) => evidence({ sourceType: "OTHER", entityType: "PerformanceVarianceCase", entityId: item.id, evidenceRef: `performance:variance:${item.id}`, label: `${item.code} · ${item.title}`, value: String(item.cashVariance) })) }; } }),
    makeTool({ name: "getRootCauseInvestigations", description: "Consulta hipóteses, evidências, causas parciais e dependências externas.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const people = await getPeoplePerformanceWorkspace({ organizationId: c.organizationId, role: "VIEWER" }, c.workspace.bundle.projectId); const cases = people.varianceCases.filter((item) => item.investigation); return { name: "getRootCauseInvestigations", mode: "READ_ONLY", status: "COMPLETED", data: cases, evidence: cases.map((item) => evidence({ sourceType: "OTHER", entityType: "RootCauseInvestigation", entityId: item.investigation!.id, evidenceRef: `performance:root-cause:${item.investigation!.id}`, label: `Causa-raiz · ${item.code}` })) }; } }),
    makeTool({ name: "getCorrectiveActions", description: "Consulta plano de ação, prazos, responsáveis, bloqueios e evidências de conclusão.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const people = await getPeoplePerformanceWorkspace({ organizationId: c.organizationId, role: "VIEWER" }, c.workspace.bundle.projectId); const actions = people.varianceCases.flatMap((item) => item.investigation?.actions ?? []); return { name: "getCorrectiveActions", mode: "READ_ONLY", status: "COMPLETED", data: actions, evidence: actions.map((item) => evidence({ sourceType: "OTHER", entityType: "CorrectiveAction", entityId: item.id, evidenceRef: `performance:action:${item.id}`, label: `${item.title} · ${item.status}` })) }; } }),
    makeTool({ name: "getAccountingResult", description: "Consulta resultado contábil determinístico por empreendimento.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getAccountingResult", mode: "READ_ONLY", status: "COMPLETED", data: { revenue: accounting.summary.recognizedRevenue, cost: accounting.summary.accountedCost, grossMargin: accounting.summary.grossMargin, operatingResult: accounting.summary.operatingResult }, evidence: accounting.entries.map((entry) => evidence({ sourceType: "OTHER", entityType: "AccountingEntry", entityId: entry.id, version: entry.entryNumber, evidenceRef: `accounting:entry:${entry.id}`, label: `${entry.entryNumber} · ${entry.description}`, value: String(entry.totalDebit) })) }; } }),
    makeTool({ name: "getTrialBalance", description: "Consulta balancete formado exclusivamente pelo razão.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getTrialBalance", mode: "READ_ONLY", status: "COMPLETED", data: accounting.trialBalance, evidence: [evidence({ sourceType: "OTHER", entityType: "TrialBalance", entityId: accounting.projectId, evidenceRef: `accounting:trial-balance:${accounting.projectId}`, label: "Balancete contábil" })] }; } }),
    makeTool({ name: "getGeneralLedgerDrilldown", description: "Consulta razão e drill-down até o evento operacional de origem.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getGeneralLedgerDrilldown", mode: "READ_ONLY", status: "COMPLETED", data: accounting.entries, evidence: accounting.entries.map((entry) => evidence({ sourceType: "OTHER", entityType: "AccountingEntry", entityId: entry.id, evidenceRef: `accounting:entry:${entry.id}`, label: `${entry.entryNumber} · ${entry.source}` })) }; } }),
    makeTool({ name: "getRealEstateInventoryPosition", description: "Consulta posição do estoque imobiliário e pools de custo.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getRealEstateInventoryPosition", mode: "READ_ONLY", status: "COMPLETED", data: accounting.inventory, evidence: accounting.inventory.pools.map((pool) => evidence({ sourceType: "OTHER", entityType: "InventoryCostPool", entityId: pool.id, evidenceRef: `accounting:inventory:${pool.id}`, label: `${pool.code} · ${pool.name}`, value: String(pool.totalAmount) })) }; } }),
    makeTool({ name: "getUnitAccountingCost", description: "Consulta apropriações de custo por unidade com prova-zero.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getUnitAccountingCost", mode: "READ_ONLY", status: "COMPLETED", data: accounting.inventory.allocations }; } }),
    makeTool({ name: "compareFinancialToAccounting", description: "Compara Financeiro e razão sem criar ajuste automático.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "compareFinancialToAccounting", mode: "READ_ONLY", status: "COMPLETED", data: accounting.reconciliations, evidence: accounting.reconciliations.map((item) => evidence({ sourceType: "OTHER", entityType: "AccountingReconciliation", entityId: item.id, evidenceRef: `accounting:reconciliation:${item.id}`, label: `${item.type} · ${item.status}`, value: String(item.differenceAmount) })) }; } }),
    makeTool({ name: "getAccountingCloseStatus", description: "Consulta períodos contábeis, fechamento e snapshots históricos.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getAccountingCloseStatus", mode: "READ_ONLY", status: "COMPLETED", data: accounting.periods }; } }),
    makeTool({ name: "getUnclassifiedAccountingEvents", description: "Lista eventos contábeis sem mapeamento vigente.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getUnclassifiedAccountingEvents", mode: "READ_ONLY", status: "COMPLETED", data: accounting.events.filter((event) => event.status === "PENDING_MAPPING") }; } }),
    makeTool({ name: "getIntercompanyEliminations", description: "Consulta eliminações intercompany e prova-zero da consolidação.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getIntercompanyEliminations", mode: "READ_ONLY", status: "COMPLETED", data: accounting.consolidations }; } }),
    makeTool({ name: "compareManagerialAndStatutoryResult", description: "Compara visões gerencial e contábil sobre os mesmos lançamentos.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "compareManagerialAndStatutoryResult", mode: "READ_ONLY", status: "COMPLETED", data: { statutoryRevenue: accounting.summary.recognizedRevenue, managerialRevenue: accounting.summary.managerialRevenue, difference: accounting.summary.managerialRevenue - accounting.summary.recognizedRevenue } }; } }),
    makeTool({ name: "getTaxesDue", description: "Consulta apurações e tributos a vencer conforme configuração aprovada.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getTaxesDue", mode: "READ_ONLY", status: "COMPLETED", data: accounting.fiscal, evidence: accounting.fiscal.assessments.map((item) => evidence({ sourceType: "OTHER", entityType: "TaxAssessment", entityId: item.id, evidenceRef: `accounting:tax:${item.id}`, label: `${item.taxCode} · ${item.status}`, value: String(item.amount) })) }; } }),
    makeTool({ name: "explainMarginBridge", description: "Explica a ponte operacional até contabilizado e pago.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const accounting = await getAccountingWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "explainMarginBridge", mode: "READ_ONLY", status: "COMPLETED", data: accounting.controllership }; } }),
    makeTool({ name: "getScore", description: "Consulta REDE Score.", mode: "READ_ONLY", minimumRole: read, schema: scenarioArgumentsSchema, async execute(c, a) { const s = scenarioOf(c, a); const score = c.workspace.bundle.scores[s]; return { name: "getScore", mode: "READ_ONLY", status: "COMPLETED", data: score, evidence: [evidence({ sourceType: "SCORE", entityType: "Score", entityId: `${c.workspace.bundle.studyVersionId}:${s}`, version: score.policyVersion, scenario: s, field: "totalScore", evidenceRef: `score:${c.workspace.bundle.studyVersionId}:${s}`, label: `REDE Score · v${c.workspace.bundle.studyVersionNumber} · ${s}`, value: String(score.totalScore) })] }; } }),
    makeTool({ name: "getScoreExplanation", description: "Explica dimensões, gates e penalidades do Score.", mode: "READ_ONLY", minimumRole: read, schema: scenarioArgumentsSchema, async execute(c, a) { const s = scenarioOf(c, a); const score = c.workspace.bundle.scores[s]; return { name: "getScoreExplanation", mode: "READ_ONLY", status: "COMPLETED", data: { totalScore: score.totalScore, classification: score.classification, dimensions: score.dimensions, gates: score.gates, penalties: score.penalties, explanation: score.explanation }, evidence: [evidence({ sourceType: "SCORE", entityType: "Score", entityId: `${c.workspace.bundle.studyVersionId}:${s}`, version: score.policyVersion, scenario: s, evidenceRef: `score:${c.workspace.bundle.studyVersionId}:${s}:explanation`, label: `Score explicado · ${s}` })] }; } }),
    makeTool({ name: "getSensitivity", description: "Consulta matriz de sensibilidade.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getSensitivity", mode: "READ_ONLY", status: "COMPLETED", data: { ranking: c.workspace.bundle.sensitivity.ranking, cases: c.workspace.bundle.sensitivity.cases }, evidence: [evidence({ sourceType: "ENGINE", entityType: "SensitivityAnalysis", entityId: c.workspace.bundle.studyVersionId, version: c.workspace.bundle.sensitivity.configVersion, scenario: c.workspace.bundle.sensitivity.scenario, evidenceRef: `sensitivity:${c.workspace.bundle.studyVersionId}`, label: "Sensitivity Engine" })] }; } }),
    makeTool({ name: "getStressTests", description: "Consulta stress tests persistidos.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getStressTests", mode: "READ_ONLY", status: "COMPLETED", data: c.workspace.bundle.sensitivity.stresses, evidence: [evidence({ sourceType: "ENGINE", entityType: "StressTest", entityId: c.workspace.bundle.studyVersionId, evidenceRef: `stress:${c.workspace.bundle.studyVersionId}`, label: "Stress Tests" })] }; } }),
    makeTool({ name: "getBreakEven", description: "Consulta break-even determinístico.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getBreakEven", mode: "READ_ONLY", status: "COMPLETED", data: c.workspace.bundle.sensitivity.breakEvens, evidence: [evidence({ sourceType: "ENGINE", entityType: "BreakEven", entityId: c.workspace.bundle.studyVersionId, evidenceRef: `break-even:${c.workspace.bundle.studyVersionId}`, label: "Break-even" })] }; } }),
    makeTool({ name: "getRedTeam", description: "Consulta conclusão e findings do Red Team.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const report = c.workspace.bundle.redTeam; const runId = c.workspace.bundle.redTeamRunId ?? c.workspace.bundle.studyVersionId; return { name: "getRedTeam", mode: "READ_ONLY", status: "COMPLETED", data: report ?? { unavailable: true }, evidence: report ? [evidence({ sourceType: "RED_TEAM", entityType: "RedTeamRun", entityId: runId, version: report.redTeamVersion, evidenceRef: `redteam:${runId}`, label: `Red Team · ${report.redTeamVersion}` })] : [] }; } }),
    makeTool({ name: "getFindings", description: "Consulta findings do Red Team.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getFindings", mode: "READ_ONLY", status: "COMPLETED", data: c.workspace.bundle.redTeam?.findings ?? [], evidence: c.workspace.bundle.redTeam?.findings.map((item) => evidence({ sourceType: "RED_TEAM", entityType: "RedTeamFinding", entityId: item.id, evidenceRef: `redteam:${c.workspace.bundle.redTeamRunId}:${item.id}`, confidence: item.confidence, label: `${item.severity} · ${item.title}` })) ?? [] }; } }),
    makeTool({ name: "getDesignReview", description: "Consulta a revisão atual do Design Intelligence sem inventar geometria.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const design = c.design; return { name: "getDesignReview", mode: "READ_ONLY", status: "COMPLETED", data: design ? { package: design.package, revision: design.revision, summary: design.summary, scorecard: design.scorecard, insights: design.insights, limitations: design.package.limitations, alternatives: design.alternatives } : { unavailable: true, reason: "Design Intelligence ainda não possui Project Package." }, evidence: design ? [evidence({ sourceType: "DESIGN", entityType: "DesignRevision", entityId: design.revision.id, version: design.revision.label, evidenceRef: `design:${design.package.id}:revision:${design.revision.id}`, confidence: design.package.preflightStatus === "READY" ? "HIGH" : "MEDIUM", label: `Design Intelligence · ${design.revision.label}` })] : [] }; } }),
    makeTool({ name: "getDesignMetrics", description: "Consulta áreas, eficiência, unidades, vagas e drift com origem e confiança.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const metrics = c.design?.metrics ?? []; return { name: "getDesignMetrics", mode: "READ_ONLY", status: "COMPLETED", data: metrics, evidence: metrics.flatMap((metric) => metric.evidenceRefs.map((ref) => evidence({ sourceType: "DESIGN", entityType: "DesignMetric", entityId: metric.id, field: metric.name, version: c.design?.revision.label, evidenceRef: ref, confidence: aiDesignConfidence(metric.confidence), label: `${metric.name} · ${metric.origin}`, value: `${metric.value} ${metric.unit}` }))) }; } }),
    makeTool({ name: "getDesignFindings", description: "Consulta findings técnicos do projeto, distintos do Red Team.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const findings = c.design?.findings ?? []; return { name: "getDesignFindings", mode: "READ_ONLY", status: "COMPLETED", data: findings, evidence: findings.flatMap((finding) => finding.evidence.map((item) => evidence({ sourceType: "DESIGN", entityType: "DesignFinding", entityId: finding.id, documentId: finding.fileId, version: c.design?.revision.label, evidenceRef: item.ref, confidence: aiDesignConfidence(item.confidence), label: `${finding.severity} · ${finding.title}`, value: item.value, location: item.page || item.region ? JSON.stringify({ page: item.page, region: item.region }) : undefined }))) }; } }),
    makeTool({ name: "getDesignOpportunities", description: "Consulta oportunidades de Value Engineering, impacto, esforço e confiança.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const opportunities = c.design?.opportunities ?? []; return { name: "getDesignOpportunities", mode: "READ_ONLY", status: "COMPLETED", data: opportunities, evidence: opportunities.map((item) => evidence({ sourceType: "DESIGN", entityType: "VEOpportunity", entityId: item.id, version: c.design?.revision.label, evidenceRef: `design:${c.design?.package.id}:ve:${item.id}`, confidence: aiDesignConfidence(item.confidence), label: `${item.category} · ${item.title}`, value: item.costImpact === null ? "Impacto econômico ainda não quantificado" : String(item.costImpact) })) }; } }),
    makeTool({ name: "compareDesignRevisions", description: "Compara métricas persistidas entre revisões de projeto.", mode: "READ_ONLY", minimumRole: read, schema: { parse(value) { const raw = value as { from?: number; to?: number }; return { from: Number.isFinite(Number(raw.from)) ? Number(raw.from) : undefined, to: Number.isFinite(Number(raw.to)) ? Number(raw.to) : undefined }; } }, async execute(c, a) { if (!c.design) return { name: "compareDesignRevisions", mode: "READ_ONLY", status: "COMPLETED", data: { unavailable: true } }; const revisions = await prisma.designRevision.findMany({ where: { packageId: c.design.package.id, package: { organizationId: c.organizationId } }, include: { metrics: true }, orderBy: { versionNumber: "asc" } }); const from = revisions.find((item) => item.versionNumber === a.from) ?? revisions.at(-2); const to = revisions.find((item) => item.versionNumber === a.to) ?? revisions.at(-1); if (!from || !to || from.id === to.id) return { name: "compareDesignRevisions", mode: "READ_ONLY", status: "COMPLETED", data: { status: "NOT_VERIFIED", reason: "São necessárias duas revisões processadas para Design Diff.", revisions: revisions.map((item) => ({ version: item.versionNumber, label: item.label })) } }; const map = (items: typeof from.metrics) => items.map((item) => ({ name: item.name, value: Number(item.value), unit: item.unit, entityType: item.entityType, entityId: item.entityId ?? undefined, origin: item.origin, confidence: item.confidence, evidence: Array.isArray(item.evidence) ? item.evidence as never : [] })); const diff = compareDesignMetrics(map(from.metrics), map(to.metrics)); return { name: "compareDesignRevisions", mode: "READ_ONLY", status: "COMPLETED", data: { from: { id: from.id, version: from.versionNumber, label: from.label }, to: { id: to.id, version: to.versionNumber, label: to.label }, diff }, evidence: diff.flatMap((item) => item.evidenceRefs.map((ref) => evidence({ sourceType: "DESIGN", entityType: "DesignChange", entityId: `${from.id}:${to.id}:${item.name}`, field: item.name, version: `${from.label} → ${to.label}`, evidenceRef: ref, confidence: aiDesignConfidence(item.confidence), label: `${item.name} · ${item.kind}`, value: item.delta === null ? undefined : String(item.delta) }))) }; } }),
    makeTool({ name: "getDocuments", description: "Consulta índice autorizado do Data Room.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const docs = c.workspace.documents.filter((item) => c.permissions.canViewConfidential || item.confidentiality === "PUBLIC_INTERNAL"); return { name: "getDocuments", mode: "READ_ONLY", status: "COMPLETED", data: docs, evidence: docs.map((item) => evidence({ sourceType: "DOCUMENT", entityType: "ProjectDocument", entityId: item.id, documentId: item.id, version: `v${item.version}`, evidenceRef: `document:${item.id}:v${item.version}`, confidence: item.status === "VERIFIED" ? "HIGH" : "MEDIUM", label: `${item.title} v${item.version}` })) }; } }),
    makeTool({ name: "getDocumentStatus", description: "Consulta completude e pendências documentais.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getDocumentStatus", mode: "READ_ONLY", status: "COMPLETED", data: { completeness: c.workspace.dataRoomCompleteness, missing: c.workspace.checklist.filter((item) => !["RECEIVED", "UNDER_REVIEW", "VERIFIED"].includes(item.status)) }, evidence: c.workspace.checklist.map((item) => evidence({ sourceType: "DATA_ROOM", entityType: "DocumentChecklistItem", entityId: item.id, evidenceRef: `checklist:${item.id}`, confidence: "HIGH", label: `${item.title} · ${item.status}` })) }; } }),
    makeTool({ name: "getUrbanScenario", description: "Consulta cenário urbanístico sem confundir hipótese com lei.", mode: "READ_ONLY", minimumRole: read, schema: { parse(value) { const raw = value as { type?: string }; return { type: raw.type ?? undefined }; } }, async execute(c, a) { const land = c.workspace.bundle.land; const scenario = land?.scenarios.find((item) => item.id === c.selection.urbanScenarioId) ?? land?.scenarios.find((item) => item.type === a.type) ?? land?.scenarios.find((item) => item.id === land.selectedScenarioId); return { name: "getUrbanScenario", mode: "READ_ONLY", status: "COMPLETED", data: scenario ?? { unavailable: true }, evidence: scenario ? [evidence({ sourceType: "ZONING", entityType: "UrbanScenario", entityId: scenario.id, version: `Land v${land?.versionNumber}`, scenario: scenario.type, evidenceRef: `zoning:${scenario.id}`, confidence: scenario.status === "VERIFIED_INPUTS" ? "HIGH" : "MEDIUM", label: `${scenario.name} · ${scenario.isHypothetical ? "SIMULAÇÃO" : "Vigente"}` })] : [] }; } }),
    makeTool({ name: "getLandAsset", description: "Consulta terreno e geometria.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const asset = c.workspace.bundle.land?.landAsset; return { name: "getLandAsset", mode: "READ_ONLY", status: "COMPLETED", data: asset ?? { unavailable: true }, evidence: asset ? [evidence({ sourceType: "LAND", entityType: "LandAsset", entityId: asset.id, evidenceRef: `land:${asset.id}`, label: `Terreno · ${asset.name}` })] : [] }; } }),
    makeTool({ name: "getMasterplan", description: "Consulta masterplan selecionado.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const land = c.workspace.bundle.land; const option = land?.options.find((item) => item.id === land.selectedOptionId); return { name: "getMasterplan", mode: "READ_ONLY", status: "COMPLETED", data: option?.masterplan ?? { unavailable: true }, evidence: option ? [evidence({ sourceType: "LAND", entityType: "LandOption", entityId: option.id, evidenceRef: `land-option:${option.id}:masterplan`, label: `${option.name} · Masterplan` })] : [] }; } }),
    makeTool({ name: "getPhases", description: "Consulta fases do masterplan.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const land = c.workspace.bundle.land; const option = land?.options.find((item) => item.id === land.selectedOptionId); return { name: "getPhases", mode: "READ_ONLY", status: "COMPLETED", data: option?.masterplan.phases ?? [] }; } }),
    makeTool({ name: "getUrbanGap", description: "Consulta gap regulatório.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getUrbanGap", mode: "READ_ONLY", status: "COMPLETED", data: c.workspace.bundle.land?.gapAnalysis ?? { unavailable: true } }; } }),
    makeTool({ name: "getUrbanUplift", description: "Consulta uplift urbano-econômico.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getUrbanUplift", mode: "READ_ONLY", status: "COMPLETED", data: c.workspace.bundle.land?.upliftAnalysis ?? { unavailable: true } }; } }),
    makeTool({ name: "getCommitteeDecision", description: "Consulta decisões do Comitê.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getCommitteeDecision", mode: "READ_ONLY", status: "COMPLETED", data: { status: c.workspace.status, decisions: c.workspace.decisions, rounds: c.workspace.rounds }, evidence: c.workspace.decisions.map((item) => evidence({ sourceType: "COMMITTEE", entityType: "CommitteeDecision", entityId: item.id, version: `Round ${item.roundNumber}`, evidenceRef: `committee-decision:${item.id}`, label: `Comitê · ${item.decision}` })) }; } }),
    makeTool({ name: "getConditions", description: "Consulta condições precedentes.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getConditions", mode: "READ_ONLY", status: "COMPLETED", data: c.workspace.conditions, evidence: c.workspace.conditions.map((item) => evidence({ sourceType: "COMMITTEE", entityType: "InvestmentCondition", entityId: item.id, evidenceRef: `condition:${item.id}`, label: `${item.title} · ${item.status}` })) }; } }),
    makeTool({ name: "getBlockers", description: "Consulta blockers determinísticos.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const blockers = [...c.workspace.approvalPath.filter((item) => item.blocker && !item.resolved), ...c.workspace.conditions.filter((item) => item.isBlocker && item.status !== "VERIFIED")]; return { name: "getBlockers", mode: "READ_ONLY", status: "COMPLETED", data: blockers }; } }),
    makeTool({ name: "getRiskRegister", description: "Consulta riscos consolidados.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getRiskRegister", mode: "READ_ONLY", status: "COMPLETED", data: { redTeam: c.workspace.bundle.redTeam?.findings ?? [], urban: c.workspace.urbanTransformation.risks, issues: c.workspace.issues }, evidence: [...(c.workspace.bundle.redTeam?.findings.map((item) => evidence({ sourceType: "RED_TEAM", entityType: "RedTeamFinding", entityId: item.id, evidenceRef: `redteam:${c.workspace.bundle.redTeamRunId}:${item.id}`, confidence: item.confidence, label: item.title })) ?? []), ...c.workspace.urbanTransformation.risks.map((item) => evidence({ sourceType: "LAND", entityType: "UrbanRisk", entityId: item.id, evidenceRef: item.evidenceRef, label: item.title }))] }; } }),
    makeTool({ name: "getIssues", description: "Consulta issues.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getIssues", mode: "READ_ONLY", status: "COMPLETED", data: c.workspace.issues }; } }),
    makeTool({ name: "getCriticalPath", description: "Calcula caminho crítico sem presumir durações.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const items = c.workspace.urbanTransformation.milestones.map((item) => ({ id: item.id, title: item.title, durationMonths: null, dependencyIds: [] })); return { name: "getCriticalPath", mode: "READ_ONLY", status: "COMPLETED", data: calculateCriticalPath(items) }; } }),
    makeTool({ name: "getReadiness", description: "Consulta readiness e data quality.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getReadiness", mode: "READ_ONLY", status: "COMPLETED", data: { investment: c.workspace.readiness, dataRoom: c.workspace.dataRoomCompleteness, urban: c.workspace.urbanTransformation.readiness, label: c.workspace.urbanTransformation.readinessLabel } }; } }),
    makeTool({ name: "getActionCenter", description: "Consulta prioridades e dependências.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getActionCenter", mode: "READ_ONLY", status: "COMPLETED", data: { issues: c.workspace.issues, conditions: c.workspace.conditions, blockers: c.workspace.approvalPath.filter((item) => item.blocker && !item.resolved) } }; } }),
    makeTool({ name: "compareVersions", description: "Compara snapshots imutáveis.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "compareVersions", mode: "READ_ONLY", status: "COMPLETED", data: { history: c.workspace.bundleHistory, changes: c.workspace.changeReport }, evidence: c.workspace.changeReport.flatMap((item) => [evidence({ sourceType: "ENGINE", entityType: "InvestmentSnapshotBundle", entityId: item.previousBundleId, field: item.metric, evidenceRef: `bundle:${item.previousBundleId}:${item.metric}`, label: `Anterior · ${item.metric}`, value: item.previous }), evidence({ sourceType: "ENGINE", entityType: "InvestmentSnapshotBundle", entityId: item.currentBundleId, field: item.metric, evidenceRef: `bundle:${item.currentBundleId}:${item.metric}`, label: `Atual · ${item.metric}`, value: item.current })]) }; } }),
    makeTool({ name: "compareScenarios", description: "Compara cenários financeiros sem misturá-los.", mode: "READ_ONLY", minimumRole: read, schema: compareScenarioArgumentsSchema, async execute(c, a) { const scenarios = a.scenarios as ScenarioKey[]; const rows = scenarios.map((scenario) => ({ scenario, metrics: c.workspace.bundle.engineResults[scenario].metrics, score: c.workspace.bundle.scores[scenario] })); return { name: "compareScenarios", mode: "READ_ONLY", status: "COMPLETED", data: rows, evidence: scenarios.flatMap((scenario) => [engineEvidence(c, scenario, "npv", c.workspace.bundle.engineResults[scenario].metrics.npv), engineEvidence(c, scenario, "equityCapitalRequired", c.workspace.bundle.engineResults[scenario].metrics.equityCapitalRequired)]) }; } }),
    makeTool({ name: "createDecisionSimulation", description: "Registra simulação no Decision Sandbox, nunca no snapshot.", mode: "SIMULATION", minimumRole: simulate, schema: simulationArgumentsSchema, async execute(c, a) { const parsed = simulationArgumentsSchema.parse(a); const assumptions = applySimulationChanges(c.workspace.bundle.assumptions, parsed.changes); const changes: Partial<ProjectAssumptions> = Object.fromEntries(Object.entries(assumptions).filter(([key, value]) => JSON.stringify(value) !== JSON.stringify(c.workspace.bundle.assumptions[key as keyof ProjectAssumptions]))) as Partial<ProjectAssumptions>; const updated = await createDecisionSandbox({ userId: c.userId, organizationId: c.organizationId }, c.workspace.id, `REDE AI · ${new Date().toLocaleString("pt-BR")}`, changes); const sandbox = updated.sandboxes[0]; return { name: "createDecisionSimulation", mode: "SIMULATION", status: "COMPLETED", data: sandbox, evidence: [evidence({ sourceType: "SIMULATION", entityType: "DecisionSandbox", entityId: sandbox.id, evidenceRef: `simulation:${sandbox.id}`, label: "SIMULAÇÃO — NÃO OFICIAL" })] }; } }),
    makeTool({ name: "runEngineSimulation", description: "Executa what-if determinístico sem alterar dados oficiais.", mode: "SIMULATION", minimumRole: simulate, schema: simulationArgumentsSchema, async execute(c, a) { const parsed = simulationArgumentsSchema.parse(a); const scenario = parsed.scenario ?? c.selection.financialScenario; const assumptions = applySimulationChanges(c.workspace.bundle.assumptions, parsed.changes); const base = c.workspace.bundle.engineResults[scenario]; const simulated = calculateProject(assumptions, scenario, new Date().toISOString()); const sensitivity = calculateSensitivity(assumptions); const score = scenario === "base" ? sensitivity.baseScore : calculateRedeScore({ result: simulated, resilience: sensitivity.resilience }); return { name: "runEngineSimulation", mode: "SIMULATION", status: "COMPLETED", data: { label: "SIMULAÇÃO — NÃO OFICIAL", scenario, changes: parsed.changes, base: { metrics: base.metrics, score: c.workspace.bundle.scores[scenario], decision: analyzeRisk(base) }, simulated: { metrics: simulated.metrics, score, decision: analyzeRisk(simulated) } }, evidence: [evidence({ sourceType: "SIMULATION", entityType: "DecisionSandbox", entityId: `temporary:${Date.now()}`, scenario, evidenceRef: `simulation:temporary:${c.workspace.bundleId}`, label: "SIMULAÇÃO — NÃO OFICIAL" }), engineEvidence(c, scenario, "baseline")] }; } }),
    makeTool({ name: "runSensitivitySimulation", description: "Executa sensibilidade sobre hipótese não oficial.", mode: "SIMULATION", minimumRole: simulate, schema: simulationArgumentsSchema, async execute(c, a) { const parsed = simulationArgumentsSchema.parse(a); const assumptions = applySimulationChanges(c.workspace.bundle.assumptions, parsed.changes); return { name: "runSensitivitySimulation", mode: "SIMULATION", status: "COMPLETED", data: { label: "SIMULAÇÃO — NÃO OFICIAL", changes: parsed.changes, sensitivity: calculateSensitivity(assumptions) } }; } }),
    makeTool({ name: "calculateLandValueCeiling", description: "Calcula valor máximo suportável do terreno.", mode: "SIMULATION", minimumRole: simulate, schema: scenarioArgumentsSchema, async execute(c, a) { const scenario = scenarioOf(c, a); const result = calculateLandValueCeiling(c.workspace.bundle.assumptions, scenario, c.workspace.bundle.frozenAt); return { name: "calculateLandValueCeiling", mode: "SIMULATION", status: "COMPLETED", data: result, evidence: [engineEvidence(c, scenario, "landValueCeiling", String(result.maximumLandPrice))] }; } }),
    makeTool({ name: "calculateCostOfDelay", description: "Calcula custo determinístico do atraso.", mode: "SIMULATION", minimumRole: simulate, schema: delayArgumentsSchema, async execute(c, a) { const months = a.months as number; const [result] = calculateDelayStress(c.workspace.bundle.assumptions, c.selection.financialScenario, [months], c.workspace.bundle.frozenAt); return { name: "calculateCostOfDelay", mode: "SIMULATION", status: "COMPLETED", data: result, evidence: [engineEvidence(c, c.selection.financialScenario, `delay:${months}`)] }; } }),
    makeTool({ name: "searchInternalEvidence", description: "Busca evidências internas autorizadas.", mode: "READ_ONLY", minimumRole: read, schema: searchArgumentsSchema, async execute(c, a) { const hits = await searchInternalEvidence(c, a.query as string, a.limit as number); return { name: "searchInternalEvidence", mode: "READ_ONLY", status: "COMPLETED", data: hits.map((item) => ({ title: item.title, excerpt: item.excerpt, source: item.source })), evidence: hits.map((item) => item.evidence) }; } }),
    makeTool({ name: "generateStudioDraft", description: "Prepara geração de artefato Studio mediante confirmação.", mode: "MUTATION", minimumRole: "ADMIN", async execute() { return { name: "generateStudioDraft", mode: "MUTATION", status: "PENDING_CONFIRMATION", data: { confirmationRequired: true } }; } }),
    makeTool({ name: "runReverseZoningSolver", description: "Resolve parâmetros urbanísticos necessários.", mode: "SIMULATION", minimumRole: simulate, schema: reverseZoningArgumentsSchema, async execute(c, a) { const land = c.workspace.bundle.land; if (!land) throw new Error("Esse dado não está disponível no estudo atual."); const option = land.options.find((item) => item.id === land.selectedOptionId) ?? land.options[0]; const result = solveReverseZoning(land.landAsset, { units: a.units as number, averageUnitArea: (a.averageUnitArea as number | undefined) ?? option?.product.averageUnitArea ?? Number(c.workspace.bundle.assumptions.privateAreaPerUnitM2), minimumMarginRate: Number(c.workspace.bundle.assumptions.policy.minimumMarginRate), minimumScore: 60, maximumExposure: Number(c.workspace.bundle.assumptions.policy.maximumExposure), numberOfTowers: (a.numberOfTowers as number | undefined) ?? option?.product.numberOfTowers ?? 1, efficiency: (a.efficiency as number | undefined) ?? option?.product.targetEfficiency ?? Number(c.workspace.bundle.assumptions.efficiencyRate), unitsPerFloor: (a.unitsPerFloor as number | undefined) ?? option?.product.unitsPerFloor ?? 8, parkingRatio: option?.product.parkingRatio ?? 1 }); return { name: "runReverseZoningSolver", mode: "SIMULATION", status: "COMPLETED", data: { label: "SIMULAÇÃO URBANÍSTICA — NÃO EQUIVALE A APROVAÇÃO", result }, evidence: [evidence({ sourceType: "SIMULATION", entityType: "ReverseZoningRun", entityId: `temporary:${Date.now()}`, evidenceRef: `reverse-zoning:${land.id}:${a.units}`, label: "Reverse Zoning Solver" }), evidence({ sourceType: "LAND", entityType: "LandAsset", entityId: land.landAsset.id, field: "area", evidenceRef: `land:${land.landAsset.id}:area`, label: "Área do terreno", value: String(land.landAsset.area) })] }; } }),
    makeTool({ name: "compareUrbanScenarios", description: "Compara cenários urbanísticos e alternativas.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const land = c.workspace.bundle.land; if (!land) return { name: "compareUrbanScenarios", mode: "READ_ONLY", status: "COMPLETED", data: { unavailable: true } }; return { name: "compareUrbanScenarios", mode: "READ_ONLY", status: "COMPLETED", data: land.scenarios.map((scenario) => ({ id: scenario.id, name: scenario.name, type: scenario.type, status: scenario.status, hypothetical: scenario.isHypothetical, parameters: scenario.parameters, options: land.options.filter((item) => item.scenarioId === scenario.id).map((item) => ({ name: item.name, score: item.score.totalScore, npv: item.financialResult.metrics.npv, equity: item.financialResult.metrics.equityCapitalRequired, units: item.areaSchedule.units })) })), evidence: land.scenarios.map((scenario) => evidence({ sourceType: "ZONING", entityType: "UrbanScenario", entityId: scenario.id, scenario: scenario.type, version: `Land v${land.versionNumber}`, evidenceRef: `zoning:${scenario.id}`, confidence: scenario.status === "VERIFIED_INPUTS" ? "HIGH" : "MEDIUM", label: `${scenario.name} · ${scenario.isHypothetical ? "SIMULAÇÃO" : "Vigente"}` })) }; } }),
    makeTool({ name: "preflightMasterReport", description: "Executa preflight sem gerar relatório.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const result = await preflightMasterReport({ organizationId: c.organizationId }, c.workspace.id, "FULL_DOSSIER", "INTERNAL"); return { name: "preflightMasterReport", mode: "READ_ONLY", status: "COMPLETED", data: result.preflight }; } }),
    makeTool({ name: "getStudioArtifacts", description: "Consulta artefatos e versões Studio.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "getStudioArtifacts", mode: "READ_ONLY", status: "COMPLETED", data: c.workspace.artifacts }; } }),
    makeTool({ name: "prepareCommitteeBrief", description: "Monta briefing a partir de módulos persistidos.", mode: "READ_ONLY", minimumRole: read, async execute(c) { return { name: "prepareCommitteeBrief", mode: "READ_ONLY", status: "COMPLETED", data: { previousDecision: c.workspace.decisions.at(-1) ?? null, changes: c.workspace.changeReport, metrics: c.workspace.bundle.engineResults[c.selection.financialScenario].metrics, score: c.workspace.bundle.scores[c.selection.financialScenario], redTeam: c.workspace.bundle.redTeam?.conclusion ?? null, blockers: c.workspace.approvalPath.filter((item) => item.blocker && !item.resolved), conditions: c.workspace.conditions.filter((item) => item.status !== "VERIFIED"), risks: c.workspace.issues, missingDocuments: c.workspace.checklist.filter((item) => !["RECEIVED", "UNDER_REVIEW", "VERIFIED"].includes(item.status)), recordedGates: c.workspace.urbanTransformation.stageGates } }; } }),
    makeTool({ name: "changeContext", description: "Troca contexto explicitamente.", mode: "READ_ONLY", minimumRole: read, schema: contextChangeSchema, execute: changeContext }),
    makeTool({ name: "getIntegrationHealth", description: "Consulta saúde decomposta das integrações: disponibilidade, sucesso, latência, freshness e backlog.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getIntegrationHealth", mode: "READ_ONLY", status: "COMPLETED", data: { installations: integrations.installations, healthSnapshots: integrations.healthSnapshots }, evidence: integrations.healthSnapshots.map((item) => evidence({ sourceType: "OTHER", entityType: "IntegrationHealthSnapshot", entityId: item.id, evidenceRef: `integrations:health:${item.id}`, label: `Saúde da integração · ${item.installationId}`, value: String(item.healthScore) })) }; } }),
    makeTool({ name: "getStaleDataSources", description: "Lista instalações sem sincronização recente conforme a política de freshness.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getStaleDataSources", mode: "READ_ONLY", status: "COMPLETED", data: integrations.installations.filter((item) => item.stale) }; } }),
    makeTool({ name: "getFailedSyncRuns", description: "Lista execuções de sincronização com falha ou parciais nas últimas rodadas.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); const failed = integrations.syncRuns.filter((run) => run.status === "FAILED" || run.status === "PARTIAL"); return { name: "getFailedSyncRuns", mode: "READ_ONLY", status: "COMPLETED", data: failed, evidence: failed.map((run) => evidence({ sourceType: "OTHER", entityType: "IntegrationSyncRun", entityId: run.id, evidenceRef: `integrations:sync-run:${run.id}`, label: `${run.mode} · ${run.status}` })) }; } }),
    makeTool({ name: "getIntegrationBacklog", description: "Consulta backlog de conflitos abertos, quarentena pendente e dead-letters não resolvidos.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getIntegrationBacklog", mode: "READ_ONLY", status: "COMPLETED", data: { openConflicts: integrations.conflicts.filter((item) => item.status === "OPEN"), pendingQuarantine: integrations.quarantine.filter((item) => item.status === "PENDING"), unresolvedDeadLetters: integrations.deadLetters.filter((item) => !item.resolved) } }; } }),
    makeTool({ name: "getMappingConflicts", description: "Lista conflitos de integração pendentes e a política aplicada, sem resolver automaticamente.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getMappingConflicts", mode: "READ_ONLY", status: "COMPLETED", data: integrations.conflicts, evidence: integrations.conflicts.map((item) => evidence({ sourceType: "OTHER", entityType: "IntegrationConflict", entityId: item.id, evidenceRef: `integrations:conflict:${item.id}`, label: `${item.entityType}.${item.fieldName} · ${item.status}` })) }; } }),
    makeTool({ name: "getQuarantinedItems", description: "Lista itens em quarentena aguardando revisão humana, sem contaminar o domínio principal.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getQuarantinedItems", mode: "READ_ONLY", status: "COMPLETED", data: integrations.quarantine }; } }),
    makeTool({ name: "compareExternalAndRedeData", description: "Compara políticas de ownership e conflitos ativos entre sistema externo e REDE, sem aplicar correção automática.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "compareExternalAndRedeData", mode: "READ_ONLY", status: "COMPLETED", data: { ownershipPolicies: integrations.ownershipPolicies, conflicts: integrations.conflicts } }; } }),
    makeTool({ name: "getNewExternalDocuments", description: "Lista documentos referenciados mais recentemente via conectores (ex.: Google Drive), sem copiar bytes por padrão.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const docs = await prisma.connectorDocumentReference.findMany({ where: { organizationId: c.organizationId, projectId: c.workspace.bundle.projectId }, orderBy: { createdAt: "desc" }, take: 20 }); return { name: "getNewExternalDocuments", mode: "READ_ONLY", status: "COMPLETED", data: docs.map((item) => ({ id: item.id, name: item.name, provider: item.provider, referenceMode: item.referenceMode, webUrl: item.webUrl, modifiedAtSource: item.modifiedAtSource?.toISOString() ?? null })), evidence: docs.map((item) => evidence({ sourceType: "DOCUMENT", entityType: "ConnectorDocumentReference", entityId: item.id, evidenceRef: `integrations:document:${item.id}`, label: item.name })) }; } }),
    makeTool({ name: "getCredentialExpiryStatus", description: "Consulta credenciais expirando ou expiradas, sem expor o segredo.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getCredentialExpiryStatus", mode: "READ_ONLY", status: "COMPLETED", data: integrations.credentials }; } }),
    makeTool({ name: "getConnectorFreshness", description: "Consulta 'atualizado em' por instalação de conector — cada domínio tem sua própria política de freshness.", mode: "READ_ONLY", minimumRole: read, async execute(c) { const integrations = await getIntegrationsWorkspace({ organizationId: c.organizationId, role: c.role }, c.workspace.bundle.projectId); return { name: "getConnectorFreshness", mode: "READ_ONLY", status: "COMPLETED", data: integrations.installations.map((item) => ({ id: item.id, name: item.name, lastSyncAt: item.lastSyncAt, stale: item.stale })) }; } }),
  ];
}

export const aiToolRegistry = new AIToolRegistry();
export const aiToolInternals = { applySimulationChanges, roleRank, jsonClone };
