import type { ProjectAssumptions } from "./types";

export const DEMO_PROJECT: ProjectAssumptions = {
  projectName: "Residencial Horizonte",
  city: "Campinas",
  state: "SP",
  landAreaM2: "2000",
  units: 40,
  privateAreaPerUnitM2: "50",
  grossBuiltAreaM2: null,
  efficiencyRate: "72",
  unitPrice: "389000",
  landPrice: "2800000",
  constructionCostPerM2: "2340",
  indirectCostsRate: "8",
  contingencyRate: "5",
  taxRate: "1",
  commissionRate: "5",
  marketingRate: "2",
  approvalMonths: 8,
  constructionMonths: 18,
  salesVelocityUnitsMonth: "4",
  salesStartDelayMonths: 0,
  downPaymentRate: "10",
  duringConstructionRate: "30",
  onDeliveryRate: "60",
  financingLimit: "4000000",
  annualFinancingRate: "14",
  annualDiscountRate: "18",
  policy: {
    minimumMarginRate: "25",
    minimumRoiRate: "30",
    minimumIrrRate: "22",
    maximumExposure: "6000000",
    minimumContingencyRate: "5",
  },
};
