"use client";

import { useState } from "react";
import { AlertTriangle, Archive, BadgeDollarSign, Calculator, CheckCircle2, FileCheck2, Landmark, Scale, Waypoints } from "lucide-react";
import type { AccountingWorkspaceView } from "@/application/accounting/accounting-service";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
type Area = "visao" | "plano" | "razao" | "balancete" | "fechamento" | "estoque" | "fiscal" | "consolidacao" | "controladoria";
const areas: Array<{ key: Area; label: string }> = [
  { key: "visao", label: "Visão Geral" }, { key: "plano", label: "Plano de Contas" }, { key: "razao", label: "Razão" }, { key: "balancete", label: "Balancete e DRE" },
  { key: "fechamento", label: "Períodos e Fechamento" }, { key: "estoque", label: "Estoque e Apropriação" }, { key: "fiscal", label: "Fiscal" }, { key: "consolidacao", label: "Consolidação" }, { key: "controladoria", label: "Controladoria" },
];
const labels: Record<string, string> = { OPEN: "Aberto", UNDER_REVIEW: "Em revisão", CLOSED: "Fechado", REOPENED: "Reaberto", ADJUSTMENT: "Ajuste", POSTED: "Contabilizado", REVERSED: "Estornado", VALIDATED: "Validado", CLASSIFIED: "Classificado", PENDING_MAPPING: "Sem classificação", DIVERGENT: "Divergente", MATCHED: "Conciliado", REVIEWED: "Revisado", APPROVED: "Aprovado", ACTIVE: "Ativo", STATUTORY: "Contábil", MANAGERIAL: "Gerencial", ASSET: "Ativo", LIABILITY: "Passivo", EQUITY: "Patrimônio líquido", REVENUE: "Receita", COST: "Custo", EXPENSE: "Despesa", FINANCIAL_RESULT: "Resultado financeiro", CONTROL: "Controle", RET: "RET", PRESUMED_PROFIT: "Lucro Presumido", ACTUAL_PROFIT: "Lucro Real" };
function Status({ value }: { value: string }) { return <span className="status-pill">{labels[value] ?? value.replaceAll("_", " ")}</span>; }

export function AccountingView({ workspace }: { workspace: AccountingWorkspaceView }) {
  const [area, setArea] = useState<Area>("visao");
  const dre = [
    ["Receita reconhecida", workspace.summary.recognizedRevenue], ["(-) Custo reconhecido", -workspace.summary.accountedCost], ["Margem bruta", workspace.summary.grossMargin], ["Resultado operacional", workspace.summary.operatingResult],
  ] as const;
  return <div className="view-stack">
    <div className="scenario-switch" aria-label="Áreas de Contabilidade e Controladoria">{areas.map((item) => <button key={item.key} className={area === item.key ? "is-active" : ""} onClick={() => setArea(item.key)}>{item.label}</button>)}</div>

    {area === "visao" && <>
      <section className="metrics-grid">
        <article className="metric-card"><div><span>Receita contábil</span><BadgeDollarSign size={17} /></div><strong>{brl.format(workspace.summary.recognizedRevenue)}</strong><small>Política e corte identificados</small></article>
        <article className="metric-card"><div><span>Custo reconhecido</span><Calculator size={17} /></div><strong>{brl.format(workspace.summary.accountedCost)}</strong><small>Derivado do razão</small></article>
        <article className="metric-card"><div><span>Margem bruta</span><Scale size={17} /></div><strong>{brl.format(workspace.summary.grossMargin)}</strong><small>Receita menos custo reconhecido</small></article>
        <article className="metric-card"><div><span>Estoque imobiliário</span><Archive size={17} /></div><strong>{brl.format(workspace.summary.inventory)}</strong><small>Memória por pool e unidade</small></article>
        <article className="metric-card"><div><span>Tributos apurados</span><Landmark size={17} /></div><strong>{brl.format(workspace.summary.taxesDue)}</strong><small>Configuração demonstrativa; validação profissional</small></article>
        <article className="metric-card"><div><span>Divergências</span><AlertTriangle size={17} /></div><strong>{workspace.summary.divergences}</strong><small>Nenhum ajuste automático</small></article>
      </section>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">IDENTIDADE ECONÔMICA</span><h2>Fato original → Política → Lançamento → Demonstrativo → Evidência</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Controle</span><span>Quantidade</span><span>Regra</span></div><div className="table-row"><strong>Eventos sem classificação</strong><span>{workspace.summary.unclassifiedEvents}</span><span>Bloqueiam contabilização; regra não é inferida</span></div><div className="table-row"><strong>Períodos em aberto</strong><span>{workspace.summary.openPeriods}</span><span>Retroatividade silenciosa bloqueada</span></div><div className="table-row"><strong>Provisões ativas</strong><span>{workspace.summary.provisions}</span><span>Origem, competência, política e reversão preservadas</span></div></div></article>
      <div className="model-note"><CheckCircle2 size={20} /><div><strong>Sem dupla contagem vertical</strong><p>Contrato representa compromisso; medição pode reconhecer competência; documento confirma a obrigação; pagamento representa caixa. O principal econômico é reconhecido uma única vez.</p></div></div>
    </>}

    {area === "plano" && <div className="view-stack">{workspace.chart.map((version) => <article className="panel" key={version.id}><div className="panel-heading"><div><span className="eyebrow">PLANO VERSIONADO</span><h2>{version.chart} · v{version.version}</h2></div><Status value={version.status} /></div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Código</th><th>Conta</th><th>Categoria</th><th>Natureza</th><th>Aceita lançamento</th></tr></thead><tbody>{version.accounts.map((account) => <tr key={account.id}><td><strong>{account.code}</strong></td><td>{account.name}</td><td>{labels[account.category] ?? account.category}</td><td>{account.normalBalance === "DEBIT" ? "Devedora" : "Credora"}</td><td>{account.posting ? "Sim" : "Sintética"}</td></tr>)}</tbody></table></div></article>)}</div>}

    {area === "razao" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">RAZÃO CONTÁBIL</span><h2>Lançamento → evento → fonte operacional</h2></div></div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Lançamento</th><th>Competência</th><th>Histórico e origem</th><th>Débito</th><th>Crédito</th><th>Situação</th></tr></thead><tbody>{workspace.entries.flatMap((entry) => entry.lines.map((line, index) => <tr key={line.id}><td>{index === 0 ? <strong>{entry.entryNumber}</strong> : ""}</td><td>{new Date(entry.competenceDate).toLocaleDateString("pt-BR")}</td><td><strong>{line.accountCode} · {line.accountName}</strong><small> · {entry.source}</small></td><td>{line.side === "DEBIT" ? brl.format(line.amount) : "—"}</td><td>{line.side === "CREDIT" ? brl.format(line.amount) : "—"}</td><td><Status value={entry.status} /></td></tr>))}</tbody></table></div></article>}

    {area === "balancete" && <>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">PROVA DE SALDOS</span><h2>Balancete</h2></div></div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Conta</th><th>Saldo anterior</th><th>Débitos</th><th>Créditos</th><th>Saldo final</th></tr></thead><tbody>{workspace.trialBalance.map((row) => <tr key={row.accountId}><td><strong>{row.code} · {row.name}</strong></td><td>{brl.format(Number(row.openingBalance))}</td><td>{brl.format(Number(row.debit))}</td><td>{brl.format(Number(row.credit))}</td><td>{brl.format(Number(row.closingBalance))}</td></tr>)}</tbody></table></div></article>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">DEMONSTRAÇÃO DETERMINÍSTICA</span><h2>DRE gerencial do empreendimento</h2></div></div><div className="scenario-table">{dre.map(([label, value]) => <div className="table-row" key={label}><strong>{label}</strong><span className={value < 0 ? "negative-value" : ""}>{brl.format(value)}</span></div>)}</div></article>
    </>}

    {area === "fechamento" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">COMPETÊNCIA E HISTÓRICO</span><h2>Períodos contábeis e snapshots</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Competência</span><span>Empresa</span><span>Situação</span><span>Snapshot</span><span>Fechado em</span></div>{workspace.periods.map((period) => <div className="table-row" key={period.id}><strong>{new Date(period.referenceMonth).toLocaleDateString("pt-BR", { month: "long", year: "numeric", timeZone: "UTC" })}</strong><span>{period.companyId.slice(-8)}</span><Status value={period.status} /><span>{period.snapshot ? "Preservado" : "Em formação"}</span><span>{period.closedAt ? new Date(period.closedAt).toLocaleDateString("pt-BR") : "—"}</span></div>)}</div></article>}

    {area === "estoque" && <>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">ESTOQUE IMOBILIÁRIO</span><h2>Terreno, obra em andamento e custos apropriáveis</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Pool</span><span>Categoria</span><span>Movimentos</span><span>Total</span></div>{workspace.inventory.pools.map((pool) => <div className="table-row" key={pool.id}><strong>{pool.code} · {pool.name}</strong><span>{pool.category.replaceAll("_", " ")}</span><span>{pool.movements}</span><span>{brl.format(pool.totalAmount)}</span></div>)}</div></article>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">MEMÓRIA DE APROPRIAÇÃO</span><h2>Prova-zero por unidade</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Pool e critério</span><span>Unidades</span><span>Origem</span><span>Apropriado</span><span>Residual</span><span>Prova-zero</span></div>{workspace.inventory.allocations.map((run) => <div className="table-row" key={run.id}><strong>{run.pool} · {run.criterion}</strong><span>{run.units}</span><span>{brl.format(run.sourceAmount)}</span><span>{brl.format(run.allocatedAmount)}</span><span>{brl.format(run.residualAmount)}</span><span>{run.proofZero ? "Confirmada" : "Pendente"}</span></div>)}</div></article>
    </>}

    {area === "fiscal" && <>
      <div className="model-note"><FileCheck2 size={20} /><div><strong>Fundação fiscal configurável</strong><p>Regime, base e alíquota são versionados e dependem de aprovação profissional. Não há transmissão oficial, SPED, ECD, ECF ou emissão fiscal nesta fase.</p></div></div>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">REGIMES E APURAÇÕES</span><h2>Tributos por empresa e vigência</h2></div></div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Tributo</th><th>Competência</th><th>Base</th><th>Valor</th><th>Vencimento</th><th>Obrigação 9B</th><th>Situação</th></tr></thead><tbody>{workspace.fiscal.assessments.map((item) => <tr key={item.id}><td><strong>{item.taxCode}</strong></td><td>{new Date(item.referenceMonth).toLocaleDateString("pt-BR", { month: "2-digit", year: "numeric", timeZone: "UTC" })}</td><td>{brl.format(item.taxableBase)}</td><td>{brl.format(item.amount)}</td><td>{item.dueAt ? new Date(item.dueAt).toLocaleDateString("pt-BR") : "—"}</td><td>{item.obligationLinked ? "Vinculada" : "Pendente de aprovação"}</td><td><Status value={item.status} /></td></tr>)}</tbody></table></div></article>
    </>}

    {area === "consolidacao" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">GRUPO → EMPRESAS → SPEs</span><h2>Consolidação e eliminações auditáveis</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Período</span><span>Soma individual</span><span>Ajustes</span><span>Eliminações</span><span>Consolidado</span><span>Prova-zero</span></div>{workspace.consolidations.map((run) => <div className="table-row" key={run.id}><strong>{new Date(run.referenceMonth).toLocaleDateString("pt-BR", { month: "long", year: "numeric", timeZone: "UTC" })}</strong><span>{brl.format(run.individualAmount)}</span><span>{brl.format(run.adjustmentAmount)}</span><span>{brl.format(run.eliminationAmount)}</span><span>{brl.format(run.consolidatedAmount)}</span><span>{run.proofZero ? "Confirmada" : "Pendente"}</span></div>)}</div></article>}

    {area === "controladoria" && <>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">PONTE OPERACIONAL-CONTÁBIL</span><h2>Base Aprovada → Orçamento → Comprometido → Medido → Contabilizado → Pago</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Base Aprovada</span><span>Orçamento</span><span>Comprometido</span><span>Medido</span><span>Contabilizado</span><span>Pago</span></div><div className="table-row"><strong>{brl.format(workspace.controllership.approvedBase)}</strong><strong>{brl.format(workspace.controllership.budget)}</strong><strong>{brl.format(workspace.controllership.committed)}</strong><strong>{brl.format(workspace.controllership.measured)}</strong><strong>{brl.format(workspace.controllership.accounted)}</strong><strong>{brl.format(workspace.controllership.paid)}</strong></div></div></article>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">CONCILIAÇÃO</span><h2>Financeiro versus razão</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Controle</span><span>Fonte</span><span>Razão</span><span>Diferença</span><span>Materialidade</span><span>Situação</span></div>{workspace.reconciliations.map((item) => <div className="table-row" key={item.id}><strong>{item.type.replaceAll("_", " ")}</strong><span>{brl.format(item.sourceAmount)}</span><span>{brl.format(item.ledgerAmount)}</span><span className={item.differenceAmount ? "negative-value" : "positive-value"}>{brl.format(item.differenceAmount)}</span><span>{item.material ? "Material" : "Imaterial"}</span><Status value={item.status} /></div>)}</div></article>
      <div className="model-note"><Waypoints size={20} /><div><strong>Drill-down preservado</strong><p>Conta → lançamento → evento contábil → medição, contrato, fornecedor e evidência. Divergências viram pendências; nunca ajustes silenciosos.</p></div></div>
    </>}
  </div>;
}
