"use client";

import { useState } from "react";
import { AlertTriangle, CalendarClock, FileSearch, Gavel, Landmark, Scale, ShieldCheck } from "lucide-react";
import type { LegalWorkspaceView } from "@/application/legal/legal-service";

type Area = "visao" | "diligencia" | "imovel" | "documentos" | "achados" | "obrigacoes" | "licencas" | "contratos" | "cronograma";
const areas: Array<{ key: Area; label: string }> = [
  { key: "visao", label: "Visão Geral" }, { key: "diligencia", label: "Diligência" }, { key: "imovel", label: "Imóvel e Matrícula" }, { key: "documentos", label: "Documentos" }, { key: "achados", label: "Achados e Decisão" }, { key: "obrigacoes", label: "Obrigações" }, { key: "licencas", label: "Licenças" }, { key: "contratos", label: "Contratos do Terreno" }, { key: "cronograma", label: "Linha do Tempo" },
];
const date = new Intl.DateTimeFormat("pt-BR");
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const label = (value: string) => value.replaceAll("_", " ");
const Status = ({ value }: { value: string }) => <span className="status-pill">{label(value)}</span>;

export function LegalView({ workspace }: { workspace: LegalWorkspaceView }) {
  const [area, setArea] = useState<Area>("visao");
  const findings = workspace.cases.flatMap((item) => item.findings);
  const requests = workspace.cases.flatMap((item) => item.documentRequests);
  return <div className="view-stack">
    <div className="scenario-switch" aria-label="Áreas Jurídicas">{areas.map((item) => <button key={item.key} className={area === item.key ? "is-active" : ""} onClick={() => setArea(item.key)}>{item.label}</button>)}</div>
    {area === "visao" && <><div className="metric-grid">
      <article className="metric-card"><div><span>Prontidão jurídica</span><ShieldCheck size={17} /></div><strong>{workspace.summary.readiness.score}%</strong><small>{workspace.summary.readiness.ready ? "Pronto para decisão" : "Condições pendentes"}</small></article>
      <article className="metric-card"><div><span>Alertas abertos</span><AlertTriangle size={17} /></div><strong>{workspace.summary.openAlerts}</strong><small>{workspace.summary.overdueObligations} obrigação(ões) vencida(s)</small></article>
      <article className="metric-card"><div><span>Achados críticos</span><Scale size={17} /></div><strong>{workspace.summary.criticalFindings}</strong><small>Riscos ainda não resolvidos</small></article>
      <article className="metric-card"><div><span>Impactos no cronograma</span><CalendarClock size={17} /></div><strong>{workspace.summary.scheduleBlockers}</strong><small>Marcos jurídicos bloqueadores</small></article>
    </div><article className="panel"><div className="panel-heading"><div><span className="eyebrow">GOVERNANÇA JURÍDICA</span><h2>Evidência → achado → condição → decisão</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Dimensão</span><span>Quantidade</span><span>Leitura</span><span>Origem</span></div>{[["Casos de diligência", workspace.cases.length, "Escopo e responsáveis versionados", "Jurídico"], ["Documentos pendentes", workspace.summary.pendingDocuments, "Solicitações e checklist", "Sala de Documentos"], ["Licenças", workspace.licenses.length, "Vigência e condicionantes", "Órgãos públicos"], ["Obrigações", workspace.obligations.length, "Prazos e integração financeira", "Contratos e legislação"]].map((row) => <div className="table-row" key={String(row[0])}><strong>{row[0]}</strong><span>{row[1]}</span><span>{row[2]}</span><span>{row[3]}</span></div>)}</div></article></>}
    {area === "diligencia" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">DUE DILIGENCE</span><h2>Casos, checklist e responsáveis</h2></div></div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Caso</th><th>Escopo</th><th>Checklist</th><th>Partes</th><th>Decisão atual</th><th>Situação</th></tr></thead><tbody>{workspace.cases.map((item) => <tr key={item.id}><td><strong>{item.code} · {item.title}</strong></td><td>{item.scope}</td><td>{item.checklistItems.filter((check) => ["COMPLIANT", "RESOLVED", "WAIVED"].includes(check.status)).length}/{item.checklistItems.length}</td><td>{item.parties.length}</td><td>{item.decisions[0] ? label(item.decisions[0].decision) : "Pendente"}</td><td><Status value={item.status} /></td></tr>)}</tbody></table></div></article>}
    {area === "imovel" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">DILIGÊNCIA IMOBILIÁRIA</span><h2>Matrículas e cadastro municipal</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Referência</span><span>Titular / exercício</span><span>Origem</span><span>Situação</span></div>{workspace.registrations.map((item) => <div className="table-row" key={item.id}><strong>Matrícula {item.registrationNumber} · v{item.version}</strong><span>{item.registeredOwner}</span><span>{label(item.provenance)}</span><Status value={item.status} /></div>)}{workspace.municipalRecords.map((item) => <div className="table-row" key={item.id}><strong>IPTU {item.municipalRegistration}</strong><span>Exercício {item.fiscalYear}</span><span>{label(item.provenance)}</span><Status value={item.debtStatus} /></div>)}</div></article>}
    {area === "documentos" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">SALA DE DOCUMENTOS</span><h2>Solicitações e evidências</h2></div></div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Código</th><th>Documento</th><th>Prazo</th><th>Versão</th><th>Evidência</th><th>Situação</th></tr></thead><tbody>{requests.map((item) => <tr key={item.id}><td>{item.code}</td><td><strong>{item.title}</strong><small>{item.documentType}</small></td><td>{item.dueAt ? date.format(new Date(item.dueAt)) : "—"}</td><td>v{item.version}</td><td>{item.documentLinkId ? "Vinculada" : "Pendente"}</td><td><Status value={item.status} /></td></tr>)}</tbody></table></div></article>}
    {area === "achados" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">PARECER ESTRUTURADO</span><h2>Achados, mitigação e decisão</h2></div></div>{findings.map((item) => <div className="model-note" key={item.id}><Gavel size={20} /><div><strong>{item.code} · {item.title}</strong><p>{item.description}</p><div className="scenario-deltas"><span>{label(item.severity)}</span><span>{label(item.status)}</span><span>{item.recommendation}</span></div></div></div>)}</article>}
    {area === "obrigacoes" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">CONTROLE DE PRAZOS</span><h2>Obrigações legais e financeiras</h2></div></div><div className="data-table-scroll"><table className="data-table"><thead><tr><th>Obrigação</th><th>Autoridade</th><th>Vencimento</th><th>Valor</th><th>Financeiro</th><th>Situação</th></tr></thead><tbody>{workspace.obligations.map((item) => <tr key={item.id}><td><strong>{item.code} · {item.title}</strong><small>{item.type}</small></td><td>{item.authority ?? "—"}</td><td>{date.format(new Date(item.dueAt))}</td><td>{item.amount ? brl.format(Number(item.amount)) : "Sem efeito financeiro"}</td><td>{item.financialEvents.some((event) => event.status === "PROCESSED") ? "Gerada exatamente uma vez" : "Não gerada"}</td><td><Status value={item.status} /></td></tr>)}</tbody></table></div></article>}
    {area === "licencas" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">LICENÇAS E PROCESSOS</span><h2>Vigência, condicionantes e tramitação</h2></div></div>{workspace.licenses.map((item) => <div className="model-note" key={item.id}><Landmark size={20} /><div><strong>{item.code} · {item.title}</strong><p>{item.authority} · validade {item.expiresAt ? date.format(new Date(item.expiresAt)) : "não informada"}</p><div className="scenario-deltas"><Status value={item.status} /><span>{item.conditions.length} condicionante(s)</span></div></div></div>)}{workspace.processes.map((item) => <div className="model-note" key={item.id}><FileSearch size={20} /><div><strong>{item.code} · Processo {item.processNumber}</strong><p>{item.authority} · {item.subject}</p><Status value={item.status} /></div></div>)}</article>}
    {area === "contratos" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">AQUISIÇÃO DO TERRENO</span><h2>Condições precedentes e garantias</h2></div></div>{workspace.contracts.map((item) => <div className="model-note" key={item.id}><Scale size={20} /><div><strong>{item.number} · {item.title}</strong><p>{item.supplier.name} · {brl.format(Number(item.originalAmount))}</p><div className="scenario-deltas"><span>{item.legalConditions.length} condição(ões)</span><span>{item.legalGuarantees.length} garantia(s)</span><Status value={item.status} /></div></div></div>)}</article>}
    {area === "cronograma" && <article className="panel"><div className="panel-heading"><div><span className="eyebrow">LINHA DO TEMPO JURÍDICA</span><h2>Marcos e impacto operacional</h2></div></div><div className="scenario-table"><div className="table-row table-head"><span>Marco</span><span>Data</span><span>Impacto</span><span>Situação</span></div>{workspace.timeline.map((item) => <div className="table-row" key={item.id}><strong>{item.code} · {item.title}</strong><span>{date.format(new Date(item.plannedAt))}</span><span>{item.blocksSchedule ? `${item.impactDays} dias · bloqueador` : "Sem bloqueio"}</span><Status value={item.status} /></div>)}</div></article>}
  </div>;
}
