import { describe, expect, it, vi } from "vitest";
import { executeFinancialTransport, financialConfiguration, financialRequest, FinancialProviderError, type FinancialTransportRequest } from "./financial-provider";
const request: FinancialTransportRequest = { operation: "BANK_SYNC", targetId: "account", requestKey: "local-request", cursor: null };
describe("9P.4 local provider-neutral transport", () => {
  it.each(["DISABLED", "REAL"] as const)("blocks %s before transport", async mode => { const execute = vi.fn(); await expect(executeFinancialTransport(mode, request, new AbortController().signal, { kind: "LOCAL_SIMULATION", execute })).rejects.toThrow(); expect(execute).not.toHaveBeenCalled(); });
  it.each(["BANK_SYNC", "BUREAU_CONSULT", "FUNDING_SUBMIT", "FUNDING_STATUS"] as const)("simulates %s without network", async operation => { const fetch = vi.spyOn(globalThis, "fetch").mockRejectedValue(new Error("forbidden")); try { const result = await executeFinancialTransport("MOCK", { ...request, operation, submissionReference: "reference" }, new AbortController().signal); expect(result).toBeDefined(); expect(fetch).not.toHaveBeenCalled(); } finally { fetch.mockRestore(); } });
  it("rejects extra tenant, raw personal data and malformed money in a bank page", async () => {
    for (const value of [{ transactions: [], nextCursor: null, checkpoint: "cp", organizationId: "other" }, { transactions: [{ externalId: "id", amount: "NaN", occurredAt: "2026-09-07T00:00:00Z", direction: "CREDIT" }], nextCursor: null, checkpoint: "cp" }, { transactions: [{ externalId: "id", amount: "1.00", occurredAt: "2026-09-07T00:00:00Z", direction: "CREDIT", taxId: "raw" }], nextCursor: null, checkpoint: "cp" }]) {
      await expect(executeFinancialTransport("MOCK", request, new AbortController().signal, { kind: "LOCAL_SIMULATION", execute: async () => value })).rejects.toThrow("INVALID_RESPONSE");
    }
  });
  it("redacts arbitrary transport error messages", async () => { await expect(executeFinancialTransport("MOCK", request, new AbortController().signal, { kind: "LOCAL_SIMULATION", execute: async () => { throw new Error("raw account and secret"); } })).rejects.toThrow("FINANCIAL_TRANSPORT_FAILURE"); });
  it("preserves classified retry delays without provider messages", async () => { await expect(executeFinancialTransport("MOCK", request, new AbortController().signal, { kind: "LOCAL_SIMULATION", execute: async () => { throw new FinancialProviderError("RATE_LIMIT", "RATE_LIMIT", 1000); } })).rejects.toMatchObject({ retryAfterMs: 1000, errorClass: "RATE_LIMIT" }); });
  it("checks cancellation before and after a cooperative transport", async () => { const c = new AbortController(); const execute = vi.fn(async () => { c.abort(); return {}; }); await expect(executeFinancialTransport("MOCK", request, c.signal, { kind: "LOCAL_SIMULATION", execute })).rejects.toThrow(); await expect(executeFinancialTransport("MOCK", request, c.signal, { kind: "LOCAL_SIMULATION", execute })).rejects.toThrow(); expect(execute).toHaveBeenCalledTimes(1); });
  it("requires bounded configuration and rejects fake proof", () => { for (const raw of [{ mode: "REAL", capability: "BANK", retentionDays: 30, perMinute: 1, verified: true }, { mode: "MOCK", capability: "BANK", retentionDays: 0, perMinute: 1 }, { mode: "MOCK", capability: "BANK", retentionDays: 181, perMinute: 1 }]) expect(financialConfiguration.safeParse(raw).success).toBe(false); });
  it("requires explicit legal basis and purpose without raw tax IDs", () => { const base = { operation: "BUREAU_CONSULT", targetId: "customer", idempotencyKey: "key" }; expect(financialRequest.safeParse(base).success).toBe(false); expect(financialRequest.safeParse({ ...base, legalBasis: "CREDIT_PROTECTION", purpose: "SALE_PROPOSAL_ANALYSIS" }).success).toBe(true); expect(financialRequest.safeParse({ ...base, legalBasis: "CREDIT_PROTECTION", purpose: "SALE_PROPOSAL_ANALYSIS", taxId: "raw" }).success).toBe(false); });
  it("rejects a mismatched funding reference or premature release at submission", async () => { for (const operation of ["FUNDING_STATUS", "FUNDING_SUBMIT"] as const) await expect(executeFinancialTransport("MOCK", { ...request, operation, submissionReference: "right" }, new AbortController().signal, { kind: "LOCAL_SIMULATION", execute: async () => ({ externalId: "wrong", state: "RELEASE_REPORTED", amount: "100.00" }) })).rejects.toThrow("INVALID_RESPONSE"); });
});
